import type { BulletinPost } from './homeTypes'

export const INITIAL_BULLETIN_POSTS: BulletinPost[] = [
  {
    id: 'post-1',
    title: 'Khẩn cấp: Kiểm tra điều hòa & máy chiếu P.204 trước ca 17:30',
    content:
      'Phòng học P.204 ghi nhận lỗi điều hòa nhỏ giọt và chập chờn cáp HDMI máy chiếu. Bộ phận kỹ thuật đang xử lý. Giáo viên phụ trách ca 17:30 lớp IELTS Junior 1A chủ động nhận chìa khóa phòng P.206 dự phòng tại quầy lễ tân nếu phòng chưa khắc phục xong.',
    category: 'urgent',
    categoryLabel: 'Khẩn cấp',
    authorName: 'Nguyễn Hoàng Nam',
    authorRole: 'Quản lý cơ sở Linh Đàm',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '15 phút trước',
    isPinned: true,
    isUrgent: true,
    badgeColor: 'bg-rose-500/10 text-rose-700 dark:text-rose-400 border-rose-500/20',
    actionLabel: 'Xem chi tiết sự cố',
    actionUrl: '/app/classes',
    acknowledgedCount: 9,
    isAcknowledged: false,
  },
  {
    id: 'post-2',
    title: 'Phân luồng đưa đón học viên & mở cổng phụ số 2 cuối tuần',
    content:
      'Từ thứ Bảy (10/10), trung tâm sẽ mở thêm cổng phụ số 2 để giải tỏa ùn tắc giờ cao điểm 17:00 - 18:30. Lễ tân và bảo vệ cơ sở lưu ý hướng dẫn phụ huynh ô tô dừng đón theo sơ đồ phân luồng mới.',
    category: 'pinned',
    categoryLabel: 'Chính sách',
    authorName: 'Bộ phận Vận hành & An ninh',
    authorRole: 'Trụ sở điều hành',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    createdAt: 'Hôm nay 08:30',
    isPinned: true,
    isUrgent: false,
    badgeColor: 'bg-indigo-500/10 text-indigo-700 dark:text-indigo-400 border-indigo-500/20',
    actionLabel: 'Xem sơ đồ phân luồng',
    actionUrl: '/app/dashboard',
    acknowledgedCount: 16,
    isAcknowledged: true,
  },
  {
    id: 'post-3',
    title: 'Bàn giao ca trực sáng sang chiều - Ngày 08/10',
    content:
      'Đã hoàn tất điểm danh 4 lớp sáng (sĩ số đạt 96%). Bàn giao 3 hồ sơ học viên mới làm bài test đầu vào lúc 15:30 chiều nay (Sale Mai Anh phụ trách). Quỹ tiền mặt lẻ tại quầy bàn giao đủ 1.500.000đ.',
    category: 'handover',
    categoryLabel: 'Bàn giao ca',
    authorName: 'Trần Mai Anh',
    authorRole: 'CSM Trưởng ca sáng',
    authorAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    createdAt: '12:15',
    isPinned: false,
    isUrgent: false,
    badgeColor: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/20',
    actionLabel: 'Sổ bàn giao ca',
    actionUrl: '/app/student_operations_alert',
    acknowledgedCount: 6,
    isAcknowledged: false,
  },
  {
    id: 'post-4',
    title: 'Đã phê duyệt giáo viên dạy thay ca 17:30',
    content:
      'Thầy Trần Hải Nam nhận dạy thay ca 17:30 lớp IELTS Junior 1A (P.A101) do cô Hoàng Thị Mai xin nghỉ ốm đột xuất. Tài liệu và giáo án số 14 đã được bàn giao đầy đủ.',
    category: 'operational',
    categoryLabel: 'Dạy thay',
    authorName: 'Hệ thống tự động',
    authorRole: 'Điều phối đào tạo',
    authorAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    createdAt: '10:45',
    isPinned: false,
    isUrgent: false,
    badgeColor: 'bg-sky-500/10 text-sky-700 dark:text-sky-400 border-sky-500/20',
    actionLabel: 'Xem lịch dạy thay',
    actionUrl: '/app/calendar_class_schedule',
    acknowledgedCount: 7,
    isAcknowledged: false,
  },
  {
    id: 'post-5',
    title: '3 đơn nghỉ phép & bảo lưu học viên chờ phê duyệt',
    content:
      'Phụ huynh học viên Lê Tuấn Kiệt (Kid-02) và Đỗ Gia Hưng (IELTS-01) đã nộp đơn xin bảo lưu 2 tuần có xác nhận lý do y tế. CSM phụ trách cơ sở kiểm tra và duyệt hạn trước 16:00.',
    category: 'operational',
    categoryLabel: 'Đơn từ',
    authorName: 'Cổng tiếp nhận RinoApp',
    authorRole: 'Chăm sóc học viên',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '09:15',
    isPinned: false,
    isUrgent: false,
    badgeColor: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/20',
    actionLabel: 'Duyệt đơn ngay',
    actionUrl: '/app/student_operations_alert',
    acknowledgedCount: 4,
    isAcknowledged: false,
  },
  {
    id: 'post-6',
    title: 'Chi nhánh Linh Đàm đạt 100% chỉ số chuyên cần tuần 40',
    content:
      'Toàn bộ 12 lớp học trong tuần đạt tỷ lệ chuyên cần trên 95%, không phát sinh phản ánh tiêu cực từ phụ huynh. Ban Giám đốc gửi lời biểu dương tổ chuyên môn Math & IELTS của cơ sở!',
    category: 'notice',
    categoryLabel: 'Vinh danh',
    authorName: 'Ban Giám đốc RinoEdu',
    authorRole: 'Ban Điều Hành',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: 'Hôm qua',
    isPinned: false,
    isUrgent: false,
    badgeColor: 'bg-purple-500/10 text-purple-700 dark:text-purple-400 border-purple-500/20',
    actionLabel: 'Xem báo cáo chi tiết',
    actionUrl: '/app/dashboard',
    acknowledgedCount: 24,
    isAcknowledged: true,
  },
]
