import type { FeeTransferRecord } from '../studentOrdersTypes'

export function getFeeTransfers(studentId: string, studentName?: string): FeeTransferRecord[] {
  const displayStudentName = studentName || 'Phạm Hoàng Bách'

  return [
    {
      id: `tf-pc-1-${studentId}`,
      transferDate: '15-08-2026',
      category: 'product_conversion',
      categoryLabel: 'Chuyển đổi sản phẩm',
      ticketCode: '03650',
      executorName: 'Lê Đức Anh 4',
      productConversion: {
        remainingDepositText: 'Số tiền cọc còn lại chưa quy đổi: 0 đ',
        transferredProducts: [
          {
            name: '[IE_TUTOR] Ielts Foundation PLUS 4.0_36 buổi',
            sessions: 2,
            amountText: '438.888 đ',
          },
        ],
        originalOrderNo: 'OD798202',
        newPackage: {
          receiptCode: 'PR0000000671',
          amountText: '438.888 đ',
        },
      },
    },
    {
      id: `tf-1-${studentId}`,
      transferDate: '14-08-2026',
      category: 'fee_transfer',
      categoryLabel: 'Chuyển phí',
      ticketCode: 'CP00014156',
      executorName: 'Trần Thảo Anh 20',
      oldPackage: {
        studentName: 'Nguyễn Ngọc Diệp',
        uid: '2135678',
        sid: '191637',
        packageName: 'Chương trình Toán tư duy Tutor-Việt Nam-1:4',
        pathwayLevel: '129',
        totalSessions: 24,
        mainSessions: 24,
        completedTotalSessions: 22,
        completedMainSessions: 22,
        transferredSessionsCount: 2,
      },
      newPackage: {
        recipientStudentName: 'Nguyễn Ngọc Diệp',
        uid: '2135678',
        sid: '191637',
        packageName: 'Chương trình Toán tư duy Tutor-Việt Nam-1:6',
        pathwayLevel: '130',
        transferType: 'Chuyển phí - Ngang tiền',
        targetPackageName: '1. [Gia sư][TH] Toán Tư Duy 1:6 (1 buổi)',
        convertedSessionsLabel: '2 BUỔI',
        linkedOrderNo: 'OD803325',
      },
    },
    {
      id: `tf-2-${studentId}`,
      transferDate: '10-08-2026',
      category: 'fee_transfer',
      categoryLabel: 'Chuyển phí',
      ticketCode: 'CP00013581',
      executorName: 'Lê Thị Trà Giang 1',
      oldPackage: {
        studentName: displayStudentName,
        uid: '1792543',
        sid: '161666',
        packageName: 'Tiếng Anh School Master-Việt Nam-1:1',
        pathwayLevel: '151',
        totalSessions: 48,
        mainSessions: 48,
        completedTotalSessions: 43,
        completedMainSessions: 43,
        transferredSessionsCount: 5,
      },
      newPackage: {
        recipientStudentName: displayStudentName,
        uid: '1792543',
        sid: '161666',
        packageName: 'Chương trình Tiếng Anh School Master-Việt Nam-1:1',
        pathwayLevel: '152',
        transferType: 'Chuyển phí - Ngang tiền',
        targetPackageName: '1. [Gia sư][THCS] Tiếng Anh School Master 1:1 (1 buổi)',
        convertedSessionsLabel: '2 BUỔI',
        linkedOrderNo: 'OD794023',
      },
    },
    {
      id: `tf-pc-2-${studentId}`,
      transferDate: '01-08-2026',
      category: 'product_conversion',
      categoryLabel: 'Chuyển đổi sản phẩm',
      ticketCode: '03429',
      executorName: 'Nguyễn Như Ngọc',
      productConversion: {
        remainingDepositText: 'Số tiền cọc còn lại chưa quy đổi: 0 đ',
        transferredProducts: [
          {
            name: '[STATION] Tiếng Anh Cambridge Primary Starters_48 buổi',
            sessions: 4,
            amountText: '1.250.000 đ',
          },
        ],
        originalOrderNo: 'OD785120',
        newPackage: {
          receiptCode: 'PR0000000492',
          amountText: '1.250.000 đ',
        },
      },
    },
    {
      id: `tf-3-${studentId}`,
      transferDate: '17-06-2026',
      category: 'fee_transfer',
      categoryLabel: 'Chuyển phí',
      ticketCode: 'CP00011223',
      executorName: 'Nguyễn Như Ngọc',
      oldPackage: {
        studentName: displayStudentName,
        uid: '1792543',
        sid: '161666',
        packageName: '[Station] Tiếng Anh OMO 1:10 ( 96 buổi )',
        pathwayLevel: 'Level 3',
        totalSessions: 96,
        mainSessions: 96,
        completedTotalSessions: 8,
        completedMainSessions: 8,
        transferredSessionsCount: 88,
      },
      newPackage: {
        recipientStudentName: displayStudentName,
        uid: '1792543',
        sid: '161666',
        packageName: 'Cambridge Global Station + Gia sư',
        pathwayLevel: 'Level 4',
        transferType: 'Chuyển phí - Ngang tiền',
        targetPackageName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
        convertedSessionsLabel: '88 BUỔI',
        linkedOrderNo: 'OD765410',
      },
    },
  ]
}
