import type { DetailedOrder } from '../studentOrdersTypes'

export function getPrimaryStudentOrders(studentId: string, studentName?: string): DetailedOrder[] {
  const displayStudentName = studentName || 'Hà Phương'

  return [
    {
      id: `ord-combo-digi-${studentId}-OD795784`,
      orderNo: 'OD795784',
      orderAmountHeader: '45,528,750',
      studentId,
      studentName: 'Nguyễn Lê Mỹ An',
      customerName: '0978123456',
      customerPhone: '0978123456',
      shippingAddress: 'Tòa Landmark 81, Phường 22, Bình Thạnh, TP. Hồ Chí Minh',
      totalAmount: 45528750,
      discountAmount: 0,
      finalAmount: 45528750,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Đã nhận bank',
      paymentOption: '1 LẦN',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Station Hà Nội',
      saleBy: 'Phạm Thị Mai Chi',
      saleRep: 'Phạm Thị Mai Chi',
      saleDate: '27-06-2026',
      createdAt: '2026-06-27T18:11:38Z',
      totalPaidAmount: 45528750,
      isCurrentPackage: true,
      receipts: [
        {
          id: 'rc-795784-1',
          code: 'TNX00000263457',
          amount: 45528750,
          method: 'BANK',
          timestamp: '18:11:38 - 27/06/2026',
          status: 'THÀNH CÔNG',
        },
      ],
      detailedItems: [
        {
          productId: 'p-global-digi-288',
          productName: '[Station] Global Digi 288 buổi (2 station + 2 Digi/ Tuần)',
          quantity: 1,
          unitPrice: 45528750,
          subtotal: 45528750,
          studentName: 'Nguyễn Lê Mỹ An',
          orderType: 'Mua mới',
          durationText: '288 buổi',
          categoryName: 'Gói combo liên kết',
          programName: 'Station Global Digi',
          teacherType: 'Bản ngữ & Trợ giảng',
          packageType: 'Combo 288 buổi',
          isRenewal: false,
          isCompleted: true,
          isPaidConfirmed: true,
          isCombo: true,
          giftText: '--',
          comboItems: [
            {
              id: 'sub-st-288',
              name: '[Station] Tiếng Anh OMO_1:10_288 buổi',
              durationText: '288 buổi',
              bonusText: '--',
            },
            {
              id: 'sub-digi-288',
              name: '[DIGI] Tiếng Anh Digital_288 buổi',
              durationText: '288 buổi',
              bonusText: '--',
            },
          ],
        },
      ],
      payments: [
        {
          id: 'pay-795784-1',
          code: 'TNX00000263457',
          amount: 45528750,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '18:11:38 27/06/2026',
          status: 'completed',
          saleBy: 'Phạm Thị Mai Chi',
          paymentType: 'full',
          paymentTypeLabel: 'Đã nhận bank',
        },
      ],
      items: [
        {
          productId: 'p-global-digi-288',
          productName: '[Station] Global Digi 288 buổi (2 station + 2 Digi/ Tuần)',
          quantity: 1,
          unitPrice: 45528750,
          subtotal: 45528750,
        },
      ],
    },
    {
      id: `ord-combo-trio-${studentId}-OD819630`,
      orderNo: 'OD819630',
      orderAmountHeader: '28,900,000',
      studentId,
      studentName: 'Lê Nguyễn Bảo Hân',
      customerName: '0963355809',
      customerPhone: '0963355809',
      shippingAddress: 'Số 45 Nguyễn Tuân, Thanh Xuân, Hà Nội',
      totalAmount: 28900000,
      discountAmount: 0,
      finalAmount: 28900000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Đã nhận bank',
      paymentOption: '1 LẦN',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Vũ Thị Lan 1',
      saleRep: 'Vũ Thị Lan 1',
      saleDate: '15-08-2026',
      createdAt: '2026-08-15T09:25:10Z',
      totalPaidAmount: 28900000,
      isCurrentPackage: true,
      receipts: [
        {
          id: 'rc-819630-1',
          code: 'TNX00000281944',
          amount: 28900000,
          method: 'BANK',
          timestamp: '09:25:10 - 15/08/2026',
          status: 'THÀNH CÔNG',
        },
      ],
      detailedItems: [
        {
          productId: 'p-combo-trio-144',
          productName: '[Combo Song Ngữ] Toán Tư Duy & Tiếng Anh OMO + DIGI (144 buổi)',
          quantity: 1,
          unitPrice: 28900000,
          subtotal: 28900000,
          studentName: 'Lê Nguyễn Bảo Hân',
          orderType: 'Mua mới',
          durationText: '144 buổi',
          categoryName: 'Gói combo gia sư',
          programName: 'Song ngữ Toàn diện',
          teacherType: 'Việt Nam & Bản ngữ',
          packageType: 'Combo 144 buổi',
          isRenewal: false,
          isCompleted: true,
          isPaidConfirmed: true,
          isCombo: true,
          giftText: '1 x Balo học sinh chống gù Rino + Bộ thẻ học flashcard',
          comboItems: [
            {
              id: 'sub-trio-1',
              name: '[Station] Toán Tư Duy 1:6 Einstein_72 buổi',
              durationText: '72 buổi',
              bonusText: 'Tặng thêm 4 buổi',
            },
            {
              id: 'sub-trio-2',
              name: '[Station] Tiếng Anh OMO_1:10_72 buổi',
              durationText: '72 buổi',
              bonusText: 'Tặng thêm 2 buổi',
            },
            {
              id: 'sub-trio-3',
              name: '[DIGI] Tự học Tiếng Anh Digital App_12 tháng',
              durationText: '12 tháng',
              bonusText: '--',
            },
          ],
        },
      ],
      payments: [
        {
          id: 'pay-819630-1',
          code: 'TNX00000281944',
          amount: 28900000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '09:25:10 15/08/2026',
          status: 'completed',
          saleBy: 'Vũ Thị Lan 1',
          paymentType: 'full',
          paymentTypeLabel: 'Đã nhận bank',
        },
      ],
      items: [
        {
          productId: 'p-combo-trio-144',
          productName: '[Combo Song Ngữ] Toán Tư Duy & Tiếng Anh OMO + DIGI (144 buổi)',
          quantity: 1,
          unitPrice: 28900000,
          subtotal: 28900000,
        },
      ],
    },
    {
      id: `ord-finished-sessions-${studentId}-OD790741`,
      orderNo: 'OD790741',
      studentId,
      studentName: 'Phạm nguyên khôi',
      customerName: '0983055652',
      customerPhone: '0983055652',
      shippingAddress: 'Bắc Giang, Xã Nghĩa Hưng, Huyện Lạng Giang, Bắc Giang',
      totalAmount: 7980000,
      discountAmount: 0,
      finalAmount: 7980000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentOption: 'NHIỀU LẦN',
      hasDepositStudyNow: true,
      hasDepositPre: false,
      canConvertProduct: false, // Hết buổi -> không chuyển đổi sản phẩm
      remainingSessions: 0,
      isExpired: true,
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Bắc Giang',
      saleBy: 'Nguyễn Văn Sale',
      saleRep: 'Nguyễn Văn Sale',
      saleDate: '03-08-2026',
      createdAt: '2026-08-03T09:56:57Z',
      totalPaidAmount: 7980000,
      receipts: [
        {
          id: 'rc-790741-1',
          code: 'TNX00000271527',
          amount: 2980000,
          method: 'COD',
          timestamp: '09:56:57 - 03/08/2026',
          status: 'THÀNH CÔNG',
        },
        {
          id: 'rc-790741-2',
          code: 'TNX00000256886',
          amount: 5000000,
          method: 'BANK',
          timestamp: '11:54:32 - 30/05/2026',
          status: 'THÀNH CÔNG',
        },
      ],
      detailedItems: [
        {
          productId: 'p-cambridge-96',
          productName: '[Gia sư] Tiếng anh 1:4 _ 96 buổi _ GV VN',
          quantity: 1,
          unitPrice: 7980000,
          subtotal: 7980000,
          studentName: 'Phạm nguyên khôi',
          orderType: 'Mua mới',
          durationText: '96 buổi',
          categoryName: 'Sản phẩm gia sư',
          programName: 'Tiếng Anh Cambridge',
          teacherType: 'Việt Nam',
          packageType: '1:4 - 90 buổi',
          isRenewal: false,
          isCompleted: true,
          bonusText: 'Tăng thêm 6 buổi học',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-790741-1',
          code: 'TNX00000271527',
          amount: 2980000,
          method: 'COD',
          statusLabel: 'Thành công',
          timestamp: '03-08-2026',
          status: 'completed',
          saleBy: 'Nguyễn Văn Sale',
          paymentType: 'full',
          paymentTypeLabel: 'Thanh toán đợt 2',
          note: '[Gia sư] Tiếng anh 1:4 _ 96 buổi _ GV VN',
          convertedSessions: 36,
          convertedAmount: 2980000,
        },
        {
          id: 'pay-790741-2',
          code: 'TNX00000256886',
          amount: 5000000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '30-05-2026',
          status: 'completed',
          saleBy: 'Nguyễn Văn Sale',
          paymentType: 'deposit',
          paymentTypeLabel: 'Thanh toán đợt 1',
          note: '[Gia sư] Tiếng anh 1:4 _ 96 buổi _ GV VN',
          convertedSessions: 60,
          convertedAmount: 5000000,
        },
      ],
      items: [
        {
          productId: 'p-cambridge-96',
          productName: '[Gia sư] Tiếng anh 1:4 _ 96 buổi _ GV VN',
          quantity: 1,
          unitPrice: 7980000,
          subtotal: 7980000,
        },
      ],
    },
    {
      id: `ord-partial-payment-${studentId}-OD803291`,
      orderNo: 'OD803291',
      studentId,
      studentName: 'Phạm nguyên khôi',
      customerName: '0983055652',
      customerPhone: '0983055652',
      shippingAddress: 'Bắc Giang, Xã Nghĩa Hưng, Huyện Lạng Giang, Bắc Giang',
      totalAmount: 2990000,
      discountAmount: 0,
      finalAmount: 2990000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T4-Thanh toán 1 phần',
      paymentOption: 'NHIỀU LẦN',
      hasDepositStudyNow: true,
      hasDepositPre: false,
      paymentStatus: 'partial',
      status: 'pending',
      branch: 'RinoEdu Bắc Giang',
      saleBy: 'Nguyễn Văn Sale',
      saleRep: 'Nguyễn Văn Sale',
      saleDate: '14-08-2026',
      createdAt: '2026-08-14T15:37:57Z',
      totalPaidAmount: 100000,
      receipts: [
        {
          id: 'rc-803291-1',
          code: 'TNX00000273948',
          amount: 100000,
          method: 'BANK',
          timestamp: '15:37:57 - 14/08/2026',
          status: 'THÀNH CÔNG',
        },
      ],
      detailedItems: [
        {
          productId: 'p-cambridge-30',
          productName: '[Gia sư] Tiếng anh 1:4 _ 30 buổi _ GV VN',
          quantity: 1,
          unitPrice: 2990000,
          subtotal: 2990000,
          studentName: 'Phạm nguyên khôi',
          orderType: 'Gia hạn',
          durationText: '30 buổi',
          categoryName: 'Sản phẩm gia sư',
          programName: 'Tiếng Anh Cambridge',
          teacherType: 'Việt Nam',
          packageType: '1:4 - 30 buổi',
          isRenewal: true,
          isCompleted: false,
          bonusText: 'Tặng thêm 2 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-803291-1',
          code: 'TNX00000273948',
          amount: 100000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '14-08-2026',
          status: 'completed',
          saleBy: 'Nguyễn Văn Sale',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 100000,
          note: '[Gia sư] Tiếng anh 1:4 _ 30 buổi _ GV VN',
          convertedSessions: 1,
          convertedAmount: 100000,
          remainingConversion: {
            sessions: 29,
            amount: 2890000,
            missingAmount: 2890000,
          },
        },
      ],
      items: [
        {
          productId: 'p-cambridge-30',
          productName: '[Gia sư] Tiếng anh 1:4 _ 30 buổi _ GV VN',
          quantity: 1,
          unitPrice: 2990000,
          subtotal: 2990000,
        },
      ],
    },
    {
      id: `ord-receipts-history-${studentId}-OD772048`,
      orderNo: 'OD772048',
      studentId,
      studentName: 'Bùi Huệ Ân',
      customerName: 'Nguyễn Thị Du',
      customerPhone: '0865981348',
      shippingAddress: 'Ấp Đầu Lòng, Thị trấn Lai Uyên, Huyện Bàu Bàng, Bình Dương',
      totalAmount: 5800000,
      discountAmount: 0,
      finalAmount: 5800000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentOption: 'NHIỀU LẦN',
      hasDepositStudyNow: true,
      hasDepositPre: false,
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Bình Dương',
      saleBy: 'Trần Thị Sale',
      saleRep: 'Trần Thị Sale',
      saleDate: '08-01-2026',
      createdAt: '2026-01-08T21:15:11Z',
      totalPaidAmount: 5800000,
      receipts: [
        {
          id: 'rc-772048-1',
          code: 'TNX00000234942',
          amount: 2900000,
          method: 'COD',
          timestamp: '21:15:11 - 08/01/2026',
          status: 'THÀNH CÔNG',
        },
        {
          id: 'rc-772048-2',
          code: 'TNX00000234935',
          amount: 2900000,
          method: 'COD',
          timestamp: '20:21:53 - 08/01/2026',
          status: 'HỦY',
        },
        {
          id: 'rc-772048-3',
          code: 'TNX00000234934',
          amount: 2900000,
          method: 'COD',
          timestamp: '20:21:53 - 08/01/2026',
          status: 'HỦY',
        },
        {
          id: 'rc-772048-4',
          code: 'TNX00000231062',
          amount: 2900000,
          method: 'BANK',
          timestamp: '09:41:20 - 10/12/2025',
          status: 'THÀNH CÔNG',
        },
      ],
      detailedItems: [
        {
          productId: 'p-einstein-48',
          productName: '[Gia sư][TH] Toán Tư Duy 1:6 Einstein (48 buổi...)',
          quantity: 1,
          unitPrice: 5800000,
          subtotal: 5800000,
          studentName: 'Bùi Huệ Ân',
          orderType: 'Mua mới',
          durationText: '48 buổi',
          categoryName: 'Sản phẩm gia sư',
          programName: 'Chương trình Toán tư duy Tutor',
          teacherType: 'Việt Nam',
          packageType: '1:6 - 48 buổi',
          isRenewal: false,
          isCompleted: true,
          bonusText: 'Tặng thêm 4 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-772048-1',
          code: 'TNX00000234942',
          amount: 2900000,
          method: 'COD',
          statusLabel: 'Thành công',
          timestamp: '08-01-2026',
          status: 'completed',
          saleBy: 'Trần Thị Sale',
          paymentType: 'final',
          paymentTypeLabel: 'Thu tiền lần 2',
          note: '[Gia sư][TH] Toán Tư Duy 1:6 Einstein (48 buổi...)',
          convertedSessions: 24,
          convertedAmount: 2900000,
        },
        {
          id: 'pay-772048-4',
          code: 'TNX00000231062',
          amount: 2900000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '10-12-2025',
          status: 'completed',
          saleBy: 'Trần Thị Sale',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc lần 1',
          note: '[Gia sư][TH] Toán Tư Duy 1:6 Einstein (48 buổi...)',
          convertedSessions: 24,
          convertedAmount: 2900000,
        },
      ],
      items: [
        {
          productId: 'p-einstein-48',
          productName: '[Gia sư][TH] Toán Tư Duy 1:6 Einstein (48 buổi...)',
          quantity: 1,
          unitPrice: 5800000,
          subtotal: 5800000,
        },
      ],
    },
    {
      id: `ord-deposit-unpaid-${studentId}-DH670616`,
      orderNo: 'DH670616',
      studentId,
      studentName: 'Trương ngọc ánh',
      totalAmount: 6800000,
      discountAmount: 0,
      finalAmount: 6800000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'Đơn có cọc / Chưa thanh toán',
      paymentStatus: 'partial',
      status: 'pending',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Hà Thị Ánh 2',
      saleRep: 'Hà Thị Ánh 2',
      saleDate: '09-10-2024',
      createdAt: '2024-10-09T08:30:00Z',
      totalPaidAmount: 3400000,
      canCreateCompletionOrder: true,
      detailedItems: [
        {
          productId: 'p-670616',
          productName: '[IE_TUTOR][THCS] Skill Plus_1:6_72 buổi',
          quantity: 1,
          unitPrice: 6800000,
          subtotal: 6800000,
          studentName: 'Trương ngọc ánh',
          orderType: '--',
          durationText: '72 buổi',
          bonusText: '--',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-670616-dep',
          code: 'DH670616',
          amount: 3400000,
          method: 'BANK',
          statusLabel: 'C2-Hủy',
          timestamp: '09-10-2024',
          status: 'completed',
          saleBy: 'Hà Thị Ánh 2',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 3400000,
          isLocked: true,
        },
      ],
      items: [
        {
          productId: 'p-670616',
          productName: '[IE_TUTOR][THCS] Skill Plus_1:6_72 buổi',
          quantity: 1,
          unitPrice: 6800000,
          subtotal: 6800000,
        },
      ],
    },
    {
      id: `ord-deposit-completed-${studentId}-DH682190`,
      orderNo: 'DH682190',
      orderAmountHeader: '7,200,000',
      studentId,
      studentName: displayStudentName,
      totalAmount: 7200000,
      discountAmount: 0,
      finalAmount: 7200000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentOption: 'NHIỀU LẦN',
      hasDepositStudyNow: false,
      hasDepositPre: true,
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Hà Thị Ánh 2',
      saleRep: 'Hà Thị Ánh 2',
      saleDate: '15-11-2024',
      createdAt: '2024-11-15T09:15:00Z',
      totalPaidAmount: 7200000,
      canCreateCompletionOrder: false,
      detailedItems: [
        {
          productId: 'p-682190',
          productName: '[IE_TUTOR][THCS] Skill Master_1:6_72 buổi',
          quantity: 1,
          unitPrice: 7200000,
          subtotal: 7200000,
          studentName: displayStudentName,
          orderType: 'Mua mới',
          durationText: '72 buổi',
          bonusText: 'Tặng thêm 4 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-682190-final',
          code: 'TNX00000218942',
          amount: 3600000,
          method: 'COD',
          statusLabel: 'Thành công',
          timestamp: '20-11-2024',
          status: 'completed',
          saleBy: 'Hà Thị Ánh 2',
          paymentType: 'final',
          paymentTypeLabel: 'Thu tiền lần 2',
          isLocked: true,
        },
        {
          id: 'pay-682190-dep',
          code: 'TNX00000215891',
          amount: 3600000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '15-11-2024',
          status: 'completed',
          saleBy: 'Hà Thị Ánh 2',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc lần 1',
          isLocked: true,
        },
      ],
      items: [
        {
          productId: 'p-682190',
          productName: '[IE_TUTOR][THCS] Skill Master_1:6_72 buổi',
          quantity: 1,
          unitPrice: 7200000,
          subtotal: 7200000,
        },
      ],
    },
    {
      id: `ord-combo-deposit-once-${studentId}-DH695420`,
      orderNo: 'DH695420',
      orderAmountHeader: '18,000,000',
      studentId,
      studentName: 'Trần Minh Khang',
      totalAmount: 18000000,
      discountAmount: 0,
      finalAmount: 18000000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'Đơn có cọc / Chưa thanh toán',
      paymentOption: '1 LẦN',
      hasDepositStudyNow: false,
      hasDepositPre: true,
      paymentStatus: 'partial',
      status: 'pending',
      branch: 'RinoEdu Station Hà Nội',
      saleBy: 'Ngô Mạnh Tuân 2',
      saleRep: 'Ngô Mạnh Tuân 2',
      saleDate: '20-07-2026',
      createdAt: '2026-07-20T10:00:00Z',
      totalPaidAmount: 5000000,
      canCreateCompletionOrder: true,
      detailedItems: [
        {
          productId: 'p-combo-144',
          productName: '[Combo Tiêu Chuẩn] Toán Tư Duy & Tiếng Anh OMO (144 buổi)',
          quantity: 1,
          unitPrice: 18000000,
          subtotal: 18000000,
          studentName: 'Trần Minh Khang',
          orderType: 'Mua mới',
          durationText: '144 buổi',
          isCombo: true,
          giftText: '--',
          comboItems: [
            {
              id: 'sub-c1-1',
              name: '[Station] Toán Tư Duy 1:6_72 buổi',
              durationText: '72 buổi',
              bonusText: 'Tặng thêm 2 buổi',
            },
            {
              id: 'sub-c1-2',
              name: '[Station] Tiếng Anh OMO_1:10_72 buổi',
              durationText: '72 buổi',
              bonusText: '--',
            },
          ],
        },
      ],
      payments: [
        {
          id: 'pay-695420-dep',
          code: 'DH695420',
          amount: 5000000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '20-07-2026',
          status: 'completed',
          saleBy: 'Ngô Mạnh Tuân 2',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 5000000,
          isLocked: true,
        },
      ],
      items: [
        {
          productId: 'p-combo-144',
          productName: '[Combo Tiêu Chuẩn] Toán Tư Duy & Tiếng Anh OMO (144 buổi)',
          quantity: 1,
          unitPrice: 18000000,
          subtotal: 18000000,
        },
      ],
    },
    {
      id: `ord-combo-deposit-studynow-${studentId}-DH698835`,
      orderNo: 'DH698835',
      orderAmountHeader: '21,900,000',
      studentId,
      studentName: 'Lê Nguyễn Bảo Hân',
      totalAmount: 21900000,
      discountAmount: 0,
      finalAmount: 21900000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'Đơn cọc học luôn / Thanh toán nhiều lần',
      paymentOption: 'NHIỀU LẦN',
      hasDepositStudyNow: true,
      hasDepositPre: false,
      paymentStatus: 'partial',
      status: 'pending',
      branch: 'RinoEdu Station Hà Nội',
      saleBy: 'Ngô Mạnh Tuân 2',
      saleRep: 'Ngô Mạnh Tuân 2',
      saleDate: '14-11-2025',
      createdAt: '2025-11-14T23:37:16Z',
      totalPaidAmount: 5000000,
      canCreateCompletionOrder: true,
      detailedItems: [
        {
          productId: 'p-cambridge-global-144',
          productName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
          quantity: 1,
          unitPrice: 21900000,
          subtotal: 21900000,
          studentName: 'Lê Nguyễn Bảo Hân',
          orderType: 'Mua mới',
          durationText: '144 buổi',
          isCombo: true,
          giftText: '--',
          comboItems: [
            {
              id: 'sub-cg-1',
              name: '[Station] Tiếng Anh OMO_1:10_96 buổi',
              durationText: '96 buổi',
              bonusText: '--',
            },
            {
              id: 'sub-cg-2',
              name: '[Gia sư] Tiếng anh OMO 1:1 _ 48 buổi _ GV Phil',
              durationText: '48 buổi',
              bonusText: '--',
            },
          ],
        },
      ],
      payments: [
        {
          id: 'pay-698835-dep',
          code: 'TNX00000227842',
          amount: 5000000,
          method: 'BANK',
          statusLabel: 'Thành công',
          timestamp: '23:37:16 14/11/2025',
          status: 'completed',
          saleBy: 'Ngô Mạnh Tuân 2',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 5000000,
          isLocked: true,
          allocations: [
            {
              groupName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
              groupConvertedAmount: 5000000,
              subItems: [
                { name: '[Station] Tiếng Anh OMO_1:10_96 buổi', convertedSessions: 24, convertedAmount: 3500000 },
                { name: '[Gia sư] Tiếng anh OMO 1:1 _ 48 buổi _ GV Phil', convertedSessions: 12, convertedAmount: 1500000 },
              ],
              remainingConversion: {
                sessions: 108,
                amount: 16900000,
                missingAmount: 16900000,
              },
            },
          ],
        },
      ],
      items: [
        {
          productId: 'p-cambridge-global-144',
          productName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
          quantity: 1,
          unitPrice: 21900000,
          subtotal: 21900000,
        },
      ],
    },
    {
      id: `ord-deposit-${studentId}-DH715978`,
      orderNo: 'DH715978',
      studentId: `sibling-1-${studentId}`,
      studentName: 'Trần Hoàng An Chi',
      isOtherChild: true,
      totalAmount: 14000000,
      discountAmount: 0,
      finalAmount: 14000000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'Đơn có cọc / Đã hoàn thành phí',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Phạm Thị Thu Uyên 1',
      saleRep: 'Phạm Thị Thu Uyên 1',
      saleDate: '06-01-2025',
      createdAt: '2025-01-06T09:15:00Z',
      totalPaidAmount: 14000000,
      detailedItems: [
        {
          productId: 'p-715978',
          productName: '[Station] Toán tư duy ( 48 buổi )',
          quantity: 1,
          unitPrice: 14000000,
          subtotal: 14000000,
          isPaidConfirmed: true,
          studentName: 'Trần Hoàng An Chi',
          orderType: 'Mua mới',
          durationText: '48 buổi',
          bonusText: 'Tặng thêm 2 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-715978-dep',
          code: 'DH715978',
          amount: 1000000,
          method: 'BANK',
          statusLabel: 'T5-Đã nhận bank',
          timestamp: '06-01-2025',
          status: 'completed',
          saleBy: 'Phạm Thị Thu Uyên 1',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 1000000,
          isLocked: true,
        },
        {
          id: 'pay-718439-fin',
          code: 'DH718439',
          amount: 13000000,
          method: 'BANK',
          statusLabel: 'T5-Đã nhận bank',
          timestamp: '10-01-2025',
          status: 'completed',
          saleBy: 'Phạm Thị Thu Uyên 1',
          paymentType: 'final',
          paymentTypeLabel: 'Hoàn tất',
          finalPaymentAmount: 13000000,
        },
      ],
      items: [
        { productId: 'p-715978', productName: '[Station] Toán tư duy ( 48 buổi )', quantity: 1, unitPrice: 14000000, subtotal: 14000000 },
      ],
    },
    {
      id: `ord-deposit-${studentId}-DH715977`,
      orderNo: 'DH715977',
      studentId: `sibling-2-${studentId}`,
      studentName: 'Trần Hoàng An Nguyên',
      isOtherChild: true,
      totalAmount: 14000000,
      discountAmount: 0,
      finalAmount: 14000000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'Đơn có cọc / Đã hoàn thành phí',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Phạm Thị Thu Uyên 1',
      saleRep: 'Phạm Thị Thu Uyên 1',
      saleDate: '06-01-2025',
      createdAt: '2025-01-06T09:30:00Z',
      totalPaidAmount: 14000000,
      detailedItems: [
        {
          productId: 'p-715977',
          productName: '[Station] Toán tư duy ( 48 buổi )',
          quantity: 1,
          unitPrice: 14000000,
          subtotal: 14000000,
          isPaidConfirmed: true,
          studentName: 'Trần Hoàng An Nguyên',
          orderType: 'Mua mới',
          durationText: '48 buổi',
          bonusText: 'Tặng thêm 2 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-715977-dep',
          code: 'DH715977',
          amount: 1000000,
          method: 'BANK',
          statusLabel: 'T5-Đã nhận bank',
          timestamp: '06-01-2025',
          status: 'completed',
          saleBy: 'Phạm Thị Thu Uyên 1',
          paymentType: 'deposit',
          paymentTypeLabel: 'Cọc',
          depositAmount: 1000000,
          isLocked: true,
        },
        {
          id: 'pay-718438-fin',
          code: 'DH718438',
          amount: 13000000,
          method: 'BANK',
          statusLabel: 'T5-Đã nhận bank',
          timestamp: '10-01-2025',
          status: 'completed',
          saleBy: 'Phạm Thị Thu Uyên 1',
          paymentType: 'final',
          paymentTypeLabel: 'Hoàn tất',
          finalPaymentAmount: 13000000,
        },
      ],
      items: [
        { productId: 'p-715977', productName: '[Station] Toán tư duy ( 48 buổi )', quantity: 1, unitPrice: 14000000, subtotal: 14000000 },
      ],
    },
  ]
}
