import type { DetailedOrder } from '../studentOrdersTypes'

export function getSecondaryStudentOrders(studentId: string, displayStudentName: string): DetailedOrder[] {
  return [
    {
      id: `ord-legacy-${studentId}-OD803325`,
      orderNo: 'OD803325',
      studentId,
      studentName: 'Lê Nguyễn Bảo Hân',
      isOtherChild: true,
      totalAmount: 10700000,
      discountAmount: 0,
      finalAmount: 10700000,
      paymentMethod: 'cash',
      paymentMethodTag: 'T3-COD',
      paymentStatus: 'partial',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Trần Thảo Anh 20',
      saleRep: 'Trần Thảo Anh 20',
      saleDate: '14-08-2026',
      createdAt: '2026-08-14T09:00:00Z',
      totalPaidAmount: 2800000,
      feeTransferSummary: {
        ticketCode: 'CP00014156',
        transferDate: '14-08-2026',
        executorName: 'Trần Thảo Anh 20',
        oldPackageName: 'Chương trình Toán tư duy Tutor-Việt Nam-1:4',
        oldPathwayLevel: '129',
        oldTotalSessions: 24,
        oldMainSessions: 24,
        oldCompletedTotalSessions: 22,
        oldCompletedMainSessions: 22,
        transferredSessionsCount: 2,
        newProgramName: 'Chương trình Toán tư duy Tutor-Việt Nam-1:6',
        newPackageName: '1. [Gia sư][TH] Toán Tư Duy 1:6 (1 buổi)',
        newPathwayLevel: '130',
        transferType: 'Chuyển phí - Ngang tiền',
        convertedSessionsLabel: '2 BUỔI',
        linkedOrderNo: 'OD803325',
      },
      detailedItems: [
        {
          productId: 'p-803325',
          productName: '[Gia sư][TH] Toán Tư Duy 1:6 (96 buổi + 8 buổi ôn tập)',
          quantity: 1,
          unitPrice: 10700000,
          subtotal: 10700000,
          isPaidConfirmed: false,
          studentName: 'Lê Nguyễn Bảo Hân',
          orderType: 'Gia Hạn',
          durationText: '96 buổi',
          bonusText: 'Tặng thêm 8 buổi ôn tập',
          giftText: '1 x [Tặng kèm không bán] Toán Tư Duy 1:6 (7 buổi)',
        },
      ],
      payments: [
        {
          id: 'pay-803325-1',
          code: 'TNX00000274076',
          amount: 7900000,
          method: 'COD',
          timestamp: '09:23:52 15/08/2026',
          status: 'pending',
          statusLabel: 'Chờ xử lý',
          saleBy: 'Trần Thảo Anh 20',
          note: '[Gia sư][TH] Toán Tư Duy 1:6 (96 buổi + 8 buổi ôn tập)',
          convertedSessions: 75,
          convertedAmount: 7907000,
        },
        {
          id: 'pay-803325-2',
          code: 'TNX00000273993',
          amount: 2800000,
          method: 'Biên nhận',
          timestamp: '18:04:04 14/08/2026',
          status: 'completed',
          statusLabel: 'Thành công',
          saleBy: 'Bot Hệ Thống',
          note: '[Gia sư][TH] Toán Tư Duy 1:6 (96 buổi + 8 buổi ôn tập)',
          convertedSessions: 21,
          convertedAmount: 2793000,
        },
      ],
      items: [
        {
          productId: 'p-803325',
          productName: '[Gia sư][TH] Toán Tư Duy 1:6 (96 buổi + 8 buổi ôn tập)',
          quantity: 1,
          unitPrice: 10700000,
          subtotal: 10700000,
        },
      ],
    },
    {
      id: `ord-legacy-${studentId}-OD800436`,
      orderNo: 'OD800436',
      studentId,
      studentName: displayStudentName,
      totalAmount: 8400000,
      discountAmount: 0,
      finalAmount: 8400000,
      paymentMethod: 'cash',
      paymentMethodTag: 'T3-COD',
      paymentStatus: 'unpaid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Vũ Thị Lan 1',
      saleRep: 'Vũ Thị Lan 1',
      saleDate: '25-07-2026',
      createdAt: '2026-07-25T15:10:02Z',
      totalPaidAmount: 5000000,
      detailedItems: [
        {
          productId: 'p-800',
          productName: '[IE_TUTOR] Ielts Intermediate PLUS 5.0_40 buổi',
          quantity: 1,
          unitPrice: 8400000,
          subtotal: 8400000,
          isPaidConfirmed: false,
          studentName: displayStudentName,
          orderType: 'Gia Hạn',
          durationText: '40 buổi',
          bonusText: 'Tặng thêm 4 buổi',
          giftText: '1 x [IELTS] Khóa 5.0',
        },
      ],
      payments: [
        {
          id: 'pay-800-1',
          code: 'TNX00000269843',
          amount: 5000000,
          method: 'BANK',
          timestamp: '15:10:02 25/07/2026',
          status: 'pending',
          statusLabel: 'Chờ thanh toán',
          saleBy: 'Vũ Thị Lan 1',
          allocations: [
            {
              groupName: '[IE_TUTOR] Ielts Intermediate PLUS 5.0_40 buổi',
              groupConvertedAmount: 4895000,
              subItems: [
                { name: '[IE] Tiếng Anh Intermediate 1:1_22 buổi', convertedSessions: 22, convertedAmount: 4895000 },
              ],
              remainingConversion: {
                sessions: 18,
                amount: 3505000,
                missingAmount: 3400000,
              },
              showCompletePaymentLink: true,
            },
          ],
        },
      ],
      items: [
        { productId: 'p-800', productName: '[IE_TUTOR] Ielts Intermediate PLUS 5.0_40 buổi', quantity: 1, unitPrice: 8400000, subtotal: 8400000 },
      ],
    },
    {
      id: `ord-legacy-${studentId}-OD777752`,
      orderNo: 'OD777752',
      studentId,
      studentName: displayStudentName,
      totalAmount: 7400000,
      discountAmount: 0,
      finalAmount: 7400000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Vũ Thị Thảo Huyền 3',
      saleRep: 'Vũ Thị Thảo Huyền 3',
      saleDate: '05-02-2026',
      createdAt: '2026-02-05T10:20:00Z',
      totalPaidAmount: 7400000,
      detailedItems: [
        {
          productId: 'p-777-1',
          productName: '[IE] Tự học Ielts 4.0 ( 1 tháng )',
          quantity: 1,
          unitPrice: 0,
          subtotal: 0,
          isPaidConfirmed: true,
          studentName: displayStudentName,
          orderType: 'Gia Hạn',
          durationText: '1 tháng',
          bonusText: '--',
          giftText: '--',
        },
        {
          productId: 'p-777-2',
          productName: '[IE_TUTOR] Ielts Foundation PLUS 4.0_36 buổi',
          quantity: 1,
          unitPrice: 7400000,
          subtotal: 7400000,
          isPaidConfirmed: true,
          studentName: displayStudentName,
          orderType: 'Gia Hạn',
          durationText: '36 buổi',
          bonusText: 'Tặng thêm 2 buổi',
          giftText: '1 x [IELTS] Khóa 4.0',
        },
      ],
      payments: [
        {
          id: 'pay-777-1',
          code: 'TNX00000244795',
          amount: 7400000,
          method: 'BANK',
          timestamp: '10:20:00 05/02/2026',
          status: 'completed',
          saleBy: 'Vũ Thị Thảo Huyền 3',
          note: '[IE_TUTOR] Ielts Foundation PLUS 4.0_36 buổi',
        },
      ],
      items: [
        { productId: 'p-777-1', productName: '[IE] Tự học Ielts 4.0 ( 1 tháng )', quantity: 1, unitPrice: 0, subtotal: 0 },
        { productId: 'p-777-2', productName: '[IE_TUTOR] Ielts Foundation PLUS 4.0_36 buổi', quantity: 1, unitPrice: 7400000, subtotal: 7400000 },
      ],
    },
    {
      id: `ord-legacy-${studentId}-OD765410`,
      orderNo: 'OD765410',
      studentId,
      studentName: displayStudentName,
      totalAmount: 21900000,
      discountAmount: 0,
      finalAmount: 21900000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Ngô Mạnh Tuân 2',
      saleRep: 'Ngô Mạnh Tuân 2',
      saleDate: '14-11-2025',
      createdAt: '2025-11-14T23:37:16Z',
      totalPaidAmount: 21900000,
      feeTransferSummary: {
        ticketCode: 'CP00011223',
        transferDate: '17-06-2026',
        executorName: 'Nguyễn Như Ngọc',
        oldPackageName: '[Station] Tiếng Anh OMO 1:10 ( 96 buổi )',
        oldPathwayLevel: 'Level 3',
        oldTotalSessions: 96,
        oldMainSessions: 96,
        oldCompletedTotalSessions: 8,
        oldCompletedMainSessions: 8,
        transferredSessionsCount: 88,
        newPackageName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
        newPathwayLevel: 'Level 4',
        transferType: 'Chuyển phí - Ngang tiền',
        convertedSessionsLabel: '88 BUỔI',
        linkedOrderNo: 'OD765410',
      },
      detailedItems: [
        {
          productId: 'p-765-1',
          productName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
          quantity: 1,
          unitPrice: 20000000,
          subtotal: 20000000,
          isPaidConfirmed: true,
          studentName: displayStudentName,
          orderType: 'Mua mới',
          durationText: '144 buổi',
          bonusText: 'Tặng thêm 4 buổi gia sư',
          giftText: '--',
        },
        {
          productId: 'p-765-2',
          productName: '[Station] Học bổng Cambridge Global _ Gia sư 4 buổi + Station 8 buổi',
          quantity: 1,
          unitPrice: 1900000,
          subtotal: 1900000,
          isPaidConfirmed: true,
          studentName: displayStudentName,
          orderType: 'Mua mới',
          durationText: '12 buổi',
          bonusText: '--',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-765-1',
          code: 'TNX00000227842',
          amount: 20000000,
          method: 'BANK',
          timestamp: '23:37:16 14/11/2025',
          status: 'pending',
          statusLabel: 'Chờ thanh toán',
          saleBy: 'Ngô Mạnh Tuân 2',
          allocations: [
            {
              groupName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
              groupConvertedAmount: 20500000,
              subItems: [
                { name: '[Station] Tiếng Anh OMO_1:10_96 buổi', convertedSessions: 88, convertedAmount: 20500000 },
                { name: '[Gia sư] Tiếng anh OMO 1:1 _ 48 buổi _ GV Phil', convertedSessions: 44, convertedAmount: 0 },
              ],
              remainingConversion: {
                sessions: 24,
                amount: 5000000,
                missingAmount: 3400000,
              },
              showCompletePaymentLink: true,
            },
            {
              groupName: '[Station] Học bổng Cambridge Global _ Gia sư 4 buổi + Station 8 buổi',
              groupConvertedAmount: 0,
              subItems: [
                { name: '[Station] Tiếng Anh OMO_1:10_8 buổi', convertedSessions: 8, convertedAmount: 0 },
                { name: '[Gia sư] Tiếng anh OMO 1:1 _ 4 buổi _ GV Phil', convertedSessions: 4, convertedAmount: 0 },
              ],
            },
          ],
        },
        {
          id: 'pay-765-2',
          code: 'TNX00000227518',
          amount: 1900000,
          method: 'BANK',
          timestamp: '20:44:18 12/11/2025',
          status: 'completed',
          saleBy: 'Ngô Mạnh Tuân 2',
          allocations: [
            {
              groupName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi',
              groupConvertedAmount: 1840000,
              subItems: [
                { name: '[Station] Tiếng Anh OMO_1:10_96 buổi', convertedSessions: 8, convertedAmount: 1400000 },
                { name: '[Gia sư] Tiếng anh OMO 1:1 _ 48 buổi _ GV Phil', convertedSessions: 4, convertedAmount: 440000 },
              ],
            },
            {
              groupName: '[Station] Học bổng Cambridge Global _ Gia sư 4 buổi + Station 8 buổi',
              groupConvertedAmount: 0,
              subItems: [
                { name: '[Station] Tiếng Anh OMO_1:10_8 buổi', convertedSessions: 0, convertedAmount: 0 },
                { name: '[Gia sư] Tiếng anh OMO 1:1 _ 4 buổi _ GV Phil', convertedSessions: 0, convertedAmount: 0 },
              ],
            },
          ],
        },
      ],
      items: [
        { productId: 'p-765-1', productName: '[Station] Cambridge Global_ Gia sư 48 buổi + Station 96 buổi', quantity: 1, unitPrice: 20000000, subtotal: 20000000 },
        { productId: 'p-765-2', productName: '[Station] Học bổng Cambridge Global _ Gia sư 4 buổi + Station 8 buổi', quantity: 1, unitPrice: 1900000, subtotal: 1900000 },
      ],
    },
    {
      id: `ord-legacy-${studentId}-OD794023`,
      orderNo: 'OD794023',
      studentId,
      studentName: 'Minh Anh',
      totalAmount: 7550000,
      discountAmount: 0,
      finalAmount: 7550000,
      paymentMethod: 'bank_transfer',
      paymentMethodTag: 'T5-Thành công',
      paymentStatus: 'paid',
      status: 'completed',
      branch: 'RinoEdu Nguyễn Tuân',
      saleBy: 'Nguyễn Như Ngọc',
      saleRep: 'Nguyễn Như Ngọc',
      saleDate: '17-06-2026',
      createdAt: '2026-06-17T16:00:45Z',
      totalPaidAmount: 7550000,
      feeTransferSummary: {
        ticketCode: 'CP00013581',
        transferDate: '10-08-2026',
        executorName: 'Lê Thị Trà Giang 1',
        oldPackageName: 'Tiếng Anh School Master-Việt Nam-1:1',
        oldPathwayLevel: '151',
        oldTotalSessions: 48,
        oldMainSessions: 48,
        oldCompletedTotalSessions: 43,
        oldCompletedMainSessions: 43,
        transferredSessionsCount: 5,
        newProgramName: 'Chương trình Tiếng Anh School Master-Việt Nam-1:1',
        newPackageName: '1. [Gia sư][THCS] Tiếng Anh School Master 1:1 (1 buổi)',
        newPathwayLevel: '152',
        transferType: 'Chuyển phí - Ngang tiền',
        convertedSessionsLabel: '2 BUỔI',
        linkedOrderNo: 'OD794023',
      },
      detailedItems: [
        {
          productId: 'p-794',
          productName: '[TUTOR][THCS] Skill Builder 2.0_1:7_72 buổi',
          quantity: 1,
          unitPrice: 7550000,
          subtotal: 7550000,
          isPaidConfirmed: true,
          studentName: 'Minh Anh',
          orderType: 'Gia Hạn',
          durationText: '72 buổi',
          bonusText: 'Tặng thêm 6 buổi',
          giftText: '--',
        },
      ],
      payments: [
        {
          id: 'pay-794-1',
          code: 'TNX00000261267',
          amount: 3139583,
          method: 'COD',
          timestamp: '08:45:02 18/06/2026',
          status: 'completed',
          saleBy: 'Nguyễn Như Ngọc',
          note: '[TUTOR][THCS] Skill Builder 2.0_1:7_72 buổi',
          convertedSessions: 38,
          convertedAmount: 3229178,
        },
        {
          id: 'pay-794-2',
          code: 'TNX00000261151',
          amount: 4410417,
          method: 'BANK',
          timestamp: '16:00:45 17/06/2026',
          status: 'completed',
          saleBy: 'Đạt Hà Thắng',
        },
      ],
      items: [
        { productId: 'p-794', productName: '[TUTOR][THCS] Skill Builder 2.0_1:7_72 buổi', quantity: 1, unitPrice: 7550000, subtotal: 7550000 },
      ],
    },
  ]
}
