import { CareConditionConfig } from './careConditionsTypes'

/**
 * Mock Catalog of Care Conditions based on Confluence Appendix 01 (`PL-CSKH-01`)
 * Updated to strictly match the new Catalog metrics, Trigger Rules, and SLA methods.
 */
export const MOCK_CARE_CONDITIONS: CareConditionConfig[] = [
  {
    id: 'COND-DB-01',
    code: 'ĐB-01',
    name: 'Nghỉ không phép từ 2 buổi trong 8 buổi gần nhất',
    category: 'chuyen_can',
    nature: 'dac_biet',
    natureLabel: 'Chăm sóc đặc biệt',
    primaryRole: 'CS',
    primaryRoleLabel: 'CS + GV',
    assignedRoles: ['CS', 'GV'],
    completionPolicy: 'any_role',
    slaHours: 24,
    slaLabel: 'Trong vòng 24 giờ',
    priority: 'high',
    dataProvidedToParent: 'Bảng điểm danh & Thống kê chuyên cần',
    focusContent: [
      'Xác minh nguyên nhân nghỉ học của học viên.',
      'Đánh giá khả năng tiếp tục tham gia lớp.',
      'Thông tin nội dung bài học học viên đã bỏ lỡ.',
      'Thống nhất phương án học bù hoặc hỗ trợ kiến thức.',
    ],
    isActive: true,
    triggerRule: {
      source: 'attendance_session',
      sourceLabel: 'CSDL Buổi học',
      metric: 'att_nghi_khong_phep',
      metricLabel: 'Số buổi nghỉ không phép',
      metricUnit: 'buổi',
      operator: 'gte',
      operatorLabel: '≥ (Lớn hơn hoặc bằng)',
      thresholdValue: 2,
      windowRange: 'custom_sessions',
      windowRangeLabel: 'Kích hoạt theo buổi học (8 buổi gần nhất)',
      slaType: 'fixed_time',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: CSDL Buổi học | Chỉ số: Số buổi nghỉ không phép ≥ 2 buổi | Chu kỳ: 8 buổi gần nhất',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-DB-02',
    code: 'ĐB-02',
    name: 'Không làm bài tập từ 3 buổi trong 8 buổi gần nhất',
    category: 'hoc_tap',
    nature: 'dac_biet',
    natureLabel: 'Chăm sóc đặc biệt',
    primaryRole: 'CS',
    primaryRoleLabel: 'CS + GV',
    assignedRoles: ['CS', 'GV'],
    completionPolicy: 'all_roles',
    slaHours: 24,
    slaLabel: 'Trong vòng 24 giờ',
    priority: 'high',
    dataProvidedToParent: 'Link bài tập đính kèm & Báo cáo BTVN',
    focusContent: [
      'Thông tin các lần không hoàn thành bài tập.',
      'Tìm hiểu nguyên nhân không làm bài.',
      'Làm rõ ảnh hưởng đến tiến độ học.',
      'Thống nhất cách gia đình phối hợp và kế hoạch hoàn thành bài.',
    ],
    isActive: true,
    triggerRule: {
      source: 'homework_db',
      sourceLabel: 'CSDL BTVN',
      metric: 'hw_thieu_btvn',
      metricLabel: 'Số buổi thiếu / chưa nộp BTVN',
      metricUnit: 'buổi',
      operator: 'gte',
      operatorLabel: '≥ (Lớn hơn hoặc bằng)',
      thresholdValue: 3,
      windowRange: 'custom_sessions',
      windowRangeLabel: 'Kích hoạt theo buổi học (8 buổi gần nhất)',
      slaType: 'fixed_time',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: CSDL BTVN | Chỉ số: Thiếu BTVN ≥ 3 buổi | Chu kỳ: 8 buổi gần nhất',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-DB-03',
    code: 'ĐB-03',
    name: 'Có bài kiểm tra đạt điểm ≤ 7.0 điểm',
    category: 'hoc_tap',
    nature: 'dac_biet',
    natureLabel: 'Chăm sóc đặc biệt',
    primaryRole: 'CS',
    primaryRoleLabel: 'Chuyên viên CS',
    slaHours: 24,
    slaLabel: 'Trong vòng 24 giờ',
    priority: 'high',
    dataProvidedToParent: 'Link bài kiểm tra đính kèm',
    focusContent: [
      'Thông báo kết quả kiểm tra cho phụ huynh.',
      'Nêu rõ phần kiến thức hoặc kỹ năng chưa đạt.',
      'Phân tích nguyên nhân điểm thi thấp.',
      'Đề xuất kế hoạch củng cố và nội dung gia đình cần phối hợp.',
    ],
    isActive: true,
    triggerRule: {
      source: 'exam_grade',
      sourceLabel: 'CSDL Điểm Kiểm tra',
      metric: 'exam_any_score',
      metricLabel: 'Điểm bài kiểm tra bất kỳ',
      metricUnit: 'điểm',
      operator: 'lte',
      operatorLabel: '≤ (Nhỏ hơn hoặc bằng)',
      thresholdValue: 7.0,
      windowRange: 'realtime',
      windowRangeLabel: 'Kích hoạt tức thời (Real-time)',
      slaType: 'fixed_time',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: CSDL Điểm Kiểm tra | Chỉ số: Điểm bài kiểm tra bất kỳ ≤ 7.0 điểm',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-TH-01',
    code: 'TH-01',
    name: 'Prestudy chuẩn bị khai giảng lớp học mới',
    category: 'hanh_trinh',
    nature: 'theo_hanh_trinh',
    natureLabel: 'Theo hành trình học',
    primaryRole: 'CS',
    primaryRoleLabel: 'Chuyên viên CS',
    slaHours: 48,
    slaLabel: 'Trước buổi tiếp theo 48 giờ',
    priority: 'medium',
    dataProvidedToParent: 'Thông tin lịch học & Tài liệu chuẩn bị',
    focusContent: [
      'Xác nhận lịch khai giảng và thông tin lớp học.',
      'Hướng dẫn chuẩn bị tài liệu trước khi lên lớp.',
      'Kiểm tra khả năng tham gia buổi học đầu tiên.',
      'Giải đáp các thắc mắc vướng mắc ban đầu của gia đình.',
    ],
    isActive: true,
    triggerRule: {
      source: 'class_db',
      sourceLabel: 'CSDL Lớp học',
      metric: 'class_sap_khai_giang',
      metricLabel: 'Cảnh báo Lớp sắp khai giảng',
      metricUnit: 'mốc',
      operator: 'milestone',
      operatorLabel: 'Mốc sự kiện',
      thresholdValue: 1,
      windowRange: 'dinh_ky_hang_ngay',
      windowRangeLabel: 'Rà soát định kỳ (04:00 sáng hằng ngày)',
      slaType: 'before_next_session',
      slaUnit: 'hours',
      slaValueInput: 48,
    },
    autoTriggerRule: 'Nguồn: CSDL Lớp học | Sự kiện: Sắp khai giảng lớp',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-TH-02',
    code: 'TH-02',
    name: 'Hoàn thành buổi học đầu tiên (First Class Care)',
    category: 'hanh_trinh',
    nature: 'theo_hanh_trinh',
    natureLabel: 'Theo hành trình học',
    primaryRole: 'CS',
    primaryRoleLabel: 'Chuyên viên CS',
    slaHours: 24,
    slaLabel: 'Trong vòng 24 giờ',
    priority: 'medium',
    dataProvidedToParent: 'Thông tin buổi học & Nhận xét buổi 1',
    focusContent: [
      'Hỏi thăm trải nghiệm ban đầu của học viên.',
      'Nắm mức độ hòa nhập và phản hồi của học sinh.',
      'Tiếp nhận ý kiến đóng góp từ phụ huynh.',
      'Phối hợp giáo viên chủ nhiệm khi có vấn đề chuyên môn.',
    ],
    isActive: true,
    triggerRule: {
      source: 'attendance_session',
      sourceLabel: 'CSDL Buổi học',
      metric: 'att_theo_so_buoi',
      metricLabel: 'Điểm danh hoàn thành buổi 1',
      metricUnit: 'mốc',
      operator: 'milestone',
      operatorLabel: 'Mốc buổi học',
      thresholdValue: 1,
      windowRange: 'buoi_thu_1',
      windowRangeLabel: 'Hoàn thành buổi học thứ 1',
      slaType: 'fixed_time',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: CSDL Buổi học | Sự kiện: Buổi học thứ 1 đã xảy ra',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-TH-03',
    code: 'TH-03',
    name: 'Báo cáo mốc Mini Project / Kiểm tra học tập',
    category: 'hoc_tap',
    nature: 'theo_moc',
    natureLabel: 'Theo mốc học tập',
    primaryRole: 'GV',
    primaryRoleLabel: 'Giáo viên Chủ nhiệm',
    slaHours: 24,
    slaLabel: 'Sau buổi tiếp theo 24 giờ',
    priority: 'medium',
    dataProvidedToParent: 'Link video / Sản phẩm học viên',
    focusContent: [
      'Gửi video hoặc sản phẩm bài thuyết trình của học viên.',
      'Nhận xét chi tiết quá trình thực hiện dự án.',
      'Nêu rõ điểm học sinh làm tốt.',
      'Nêu nội dung cần tiếp tục rèn luyện.',
    ],
    isActive: true,
    triggerRule: {
      source: 'exam_grade',
      sourceLabel: 'CSDL Điểm Kiểm tra',
      metric: 'exam_midterm',
      metricLabel: 'Điểm bài kiểm tra giữa kỳ / Mini Project',
      metricUnit: 'điểm',
      operator: 'lte',
      operatorLabel: '≤ (Nhỏ hơn hoặc bằng)',
      thresholdValue: 6.5,
      windowRange: 'realtime',
      windowRangeLabel: 'Kích hoạt tức thời (Real-time)',
      slaType: 'after_next_session',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: CSDL Điểm Kiểm tra | Chỉ số: Điểm bài thi giữa kỳ ≤ 6.5 điểm',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-DK-01',
    code: 'ĐK-01',
    name: 'Kỳ rà soát báo cáo chăm sóc định kỳ hằng tháng',
    category: 'hoc_tap',
    nature: 'dinh_ky',
    natureLabel: 'Định kỳ',
    primaryRole: 'GV',
    primaryRoleLabel: 'Giáo viên Chủ nhiệm',
    slaHours: 72,
    slaLabel: 'Đến ngày cuối cùng của tháng (23:59)',
    priority: 'medium',
    dataProvidedToParent: 'Link Báo cáo tổng hợp tháng',
    focusContent: [
      'Tổng hợp kết quả học tập trong tháng.',
      'Nhận xét tiến bộ, thái độ và mức độ tiếp thu.',
      'Nêu nội dung kiến thức cần cải thiện.',
      'Đề xuất kế hoạch bài tập cá nhân hóa cho tháng tiếp theo.',
    ],
    isActive: true,
    triggerRule: {
      source: 'periodic_time',
      sourceLabel: 'Định kỳ - Theo thời gian',
      metric: 'periodic_by_date_of_month',
      metricLabel: 'Theo mốc Ngày trong tháng',
      metricUnit: 'ngày',
      operator: 'milestone',
      operatorLabel: 'Định kỳ theo mốc lịch',
      thresholdValue: 1,
      windowRange: 'ngay_1',
      windowRangeLabel: 'Rà soát định kỳ hằng tháng (04:00 sáng Ngày 1)',
      slaType: 'end_of_month',
    },
    autoTriggerRule: 'Nguồn: Định kỳ - Theo thời gian | Chỉ số: Mốc Ngày 1 hằng tháng',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-GOI-01',
    code: 'GO-01',
    name: 'Cảnh báo Gói học sắp hết hạn / còn ≤ 5 buổi học',
    category: 'dich_vu',
    nature: 'tai_phi',
    natureLabel: 'Tái phí',
    primaryRole: 'CS',
    primaryRoleLabel: 'Chuyên viên CS',
    slaHours: 24,
    slaLabel: 'Trong vòng 24 giờ',
    priority: 'high',
    dataProvidedToParent: 'Bảng theo dõi số buổi & Thời hạn gói học',
    focusContent: [
      'Thông báo số buổi còn lại trong hợp đồng cho phụ huynh.',
      'Tư vấn kế hoạch tái phí hoặc đăng ký khóa tiếp theo.',
      'Thống nhất lịch học chặng mới.',
    ],
    isActive: true,
    triggerRule: {
      source: 'subscription_package',
      sourceLabel: 'Gói đăng ký',
      metric: 'sub_so_buoi_con_lai',
      metricLabel: 'Số buổi học còn lại trong gói',
      metricUnit: 'buổi',
      operator: 'lte',
      operatorLabel: '≤ (Nhỏ hơn hoặc bằng)',
      thresholdValue: 5,
      windowRange: 'realtime',
      windowRangeLabel: 'Kích hoạt tức thời (Real-time)',
      slaType: 'fixed_time',
      slaUnit: 'hours',
      slaValueInput: 24,
    },
    autoTriggerRule: 'Nguồn: Gói đăng ký | Chỉ số: Số buổi còn lại ≤ 5 buổi',
    createdAt: '2026-07-21 08:00',
    updatedAt: '2026-07-22 10:00',
  },
  {
    id: 'COND-LH-01',
    code: 'LH-01',
    name: 'Phát sinh Đổi / Thế ca Giáo viên phụ trách',
    category: 'dich_vu',
    nature: 'dac_biet',
    natureLabel: 'Chăm sóc đặc biệt',
    primaryRole: 'CS',
    primaryRoleLabel: 'CS + GV',
    assignedRoles: ['CS', 'GV'],
    completionPolicy: 'any_role',
    slaHours: 12,
    slaLabel: 'Trước buổi tiếp theo 12 giờ',
    priority: 'high',
    dataProvidedToParent: 'Thông báo Giáo viên mới & Hồ sơ giảng dạy',
    focusContent: [
      'Thông báo lý do đổi / thế ca GV cho phụ huynh.',
      'Giới thiệu trình độ và kinh nghiệm của GV mới.',
      'Đảm bảo sự đồng bộ trong tiến độ và phương pháp giảng dạy.',
      'Ghi nhận phản hồi của phụ huynh sau buổi học đầu với GV mới.',
    ],
    isActive: true,
    triggerRule: {
      source: 'class_db',
      sourceLabel: 'CSDL Lớp học',
      metric: 'class_doi_giao_vien',
      metricLabel: 'Phát sinh Đổi / Thế ca Giáo viên phụ trách',
      metricUnit: 'mốc',
      operator: 'milestone',
      operatorLabel: 'Mốc đổi GV',
      thresholdValue: 1,
      windowRange: 'realtime',
      windowRangeLabel: 'Kích hoạt tức thời (Real-time)',
      slaType: 'before_next_session',
      slaUnit: 'hours',
      slaValueInput: 12,
    },
    autoTriggerRule: 'Nguồn: CSDL Lớp học | Sự kiện: Đổi/Thế ca Giáo viên',
    createdAt: '2026-07-23 09:00',
    updatedAt: '2026-07-23 09:00',
  },
  {
    id: 'COND-LH-02',
    code: 'LH-02',
    name: 'Phát sinh Hủy / Hoãn hoặc Đổi phòng học đột xuất',
    category: 'dich_vu',
    nature: 'dac_biet',
    natureLabel: 'Chăm sóc đặc biệt',
    primaryRole: 'CS',
    primaryRoleLabel: 'CS + GV',
    assignedRoles: ['CS', 'GV'],
    completionPolicy: 'all_roles',
    slaHours: 12,
    slaLabel: 'Trước buổi tiếp theo 12 giờ',
    priority: 'urgent',
    dataProvidedToParent: 'Lịch học điều chỉnh & Sơ đồ phòng học mới',
    focusContent: [
      'Gửi thông báo tức thời qua Zalo / SMS cho phụ huynh.',
      'Xác nhận phụ huynh đã đọc tin thông báo đổi phòng/hoãn buổi.',
      'Cung cấp lịch bù hoặc thông tin phòng học mới rõ ràng.',
    ],
    isActive: true,
    triggerRule: {
      source: 'class_db',
      sourceLabel: 'CSDL Lớp học',
      metric: 'class_huy_hoan_buoi',
      metricLabel: 'Phát sinh Hủy / Hoãn buổi học đột xuất',
      metricUnit: 'mốc',
      operator: 'milestone',
      operatorLabel: 'Mốc hoãn buổi',
      thresholdValue: 1,
      windowRange: 'realtime',
      windowRangeLabel: 'Kích hoạt tức thời (Real-time)',
      slaType: 'before_next_session',
      slaUnit: 'hours',
      slaValueInput: 12,
    },
    autoTriggerRule: 'Nguồn: CSDL Lớp học | Sự kiện: Hủy/Hoãn/Đổi phòng học',
    createdAt: '2026-07-23 09:00',
    updatedAt: '2026-07-23 09:00',
  },
]

export function getConditionNatureBadge(nature: string): { label: string; badgeClass: string } {
  switch (nature) {
    case 'dac_biet':
      return { label: 'Chăm sóc đặc biệt', badgeClass: 'bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950 dark:text-rose-300 font-medium' }
    case 'tai_phi':
      return { label: 'Tái phí', badgeClass: 'bg-teal-50 text-teal-700 border-teal-200 dark:bg-teal-950 dark:text-teal-300 font-medium' }
    case 'dinh_ky':
      return { label: 'Định kỳ', badgeClass: 'bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950 dark:text-purple-300 font-medium' }
    case 'theo_hanh_trinh':
      return { label: 'Theo hành trình', badgeClass: 'bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950 dark:text-sky-300 font-medium' }
    case 'theo_moc':
      return { label: 'Theo mốc', badgeClass: 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 font-medium' }
    case 'theo_yeu_cau':
      return { label: 'Theo yêu cầu', badgeClass: 'bg-zinc-100 text-zinc-700 border-zinc-200 dark:bg-zinc-800 dark:text-zinc-300 font-medium' }
    default:
      return { label: nature, badgeClass: 'bg-zinc-100 text-zinc-700 border-zinc-200 dark:bg-zinc-800 dark:text-zinc-300 font-medium' }
  }
}
