import {
  DataPoolConfig,
  PipelineStageConfig,
  CallDispositionConfig,
  LegacyMappingItem,
} from './leadLifecycleTypes'

export const MOCK_DATA_POOLS: DataPoolConfig[] = [
  {
    id: 'pool-m',
    code: 'M',
    name: 'Kho M',
    url: 'https://marketing.rinoedu.vn/lead-capture/kho-m',
    leadCount: 2310,
    isActive: true,
  },
  {
    id: 'pool-g',
    code: 'G',
    name: 'Kho G',
    url: 'https://rinoedu.vn/landing/workshop-gioi-thieu',
    leadCount: 450,
    isActive: true,
  },
  {
    id: 'pool-c',
    code: 'C',
    name: 'Kho CC',
    url: 'https://crm.rinoedu.vn/cskh/cham-soc-tai-phi',
    leadCount: 680,
    isActive: true,
  },
  {
    id: 'pool-t',
    code: 'T',
    name: 'Kho T',
    url: 'https://telesales.rinoedu.vn/inbound/lead-t',
    leadCount: 1240,
    isActive: true,
  },
]

export const MOCK_PIPELINE_STAGES_POOL_T: PipelineStageConfig[] = [
  {
    id: 'stage-new',
    code: 'NEW',
    name: '[T0] Tiếp nhận Lead',
    phaseGroup: 'T0',
    phaseGroupLabel: 'Tiếp nhận Lead',
    color: '#38bdf8',
    order: 1,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 12,
    actionLabel: 'Gọi tiếp cận lần đầu',
    description: 'Data mới đổ về từ Kho M, G, CC, T; tư vấn viên sàng lọc và liên hệ ban đầu',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-new-1',
        code: 'CHUA_CO_SALE',
        name: 'Mới về - Chưa phân Sale',
        color: '#64c8f5',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Sàng lọc & Phân bổ',
        systemEventTrigger: 'Data mới đổ về từ Kho',
        leadCount: 145,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-new-2',
        code: 'DA_PHAN_SALE',
        name: 'Đã giao Sale - Chưa gọi',
        color: '#38bdf8',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Phân bổ Lead',
        systemEventTrigger: 'Quản lý gán tư vấn viên',
        leadCount: 88,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-new-3',
        code: 'SO_SAI',
        name: 'Số sai / Spam / Rác',
        color: '#64748b',
        origin: 'custom',
        leadCount: 24,
        requiresNote: true,
        description: 'Số điện thoại ảo hoặc thiếu số',
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-qt',
    code: 'QT',
    name: '[T1] Đang tư vấn & Chăm sóc',
    phaseGroup: 'T1',
    phaseGroupLabel: 'Tư vấn & Chăm sóc',
    color: '#f59e0b',
    order: 2,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 48,
    actionLabel: 'Gửi lộ trình & Báo giá',
    description: 'Đã kết nối thành công, đồng bộ trực tiếp với Panel Chăm sóc Lead (Cuộc gọi, Zalo, Lịch hẹn)',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-qt-1',
        code: 'GOI_LAN_1',
        name: 'Đã gọi lần 1 (Chưa chốt)',
        color: '#fbbf24',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (CARE)',
        systemEventTrigger: 'Hoàn tất cuộc gọi lần 1 trên Panel Chăm sóc',
        description: 'Tự động ghi nhận khi Telesale kết nối thành công cuộc gọi đầu tiên và lưu trao đổi',
        leadCount: 112,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-qt-2',
        code: 'GOI_LAN_2',
        name: 'Đã gọi lần 2 (Đang chăm)',
        color: '#f59e0b',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (CARE)',
        systemEventTrigger: 'Phát sinh cuộc gọi hoặc trao đổi lần 2 từ Panel Chăm sóc',
        description: 'Hồ sơ Lead trong ca chăm sóc tích cực, duy trì chuỗi tương tác tư vấn',
        leadCount: 76,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-qt-3',
        code: 'HEN_GOI_LAI',
        name: 'Hẹn gọi lại sau',
        color: '#d97706',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (Lịch hẹn)',
        systemEventTrigger: 'Đặt lịch hẹn gọi lại (Callback) trên Panel Chăm sóc',
        suggestsCallback: true,
        description: 'Phụ huynh bận, hệ thống tự động lên lịch nhắc tư vấn viên gọi lại theo mốc giờ hẹn',
        leadCount: 65,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-qt-4',
        code: 'HOAN_TAT_CA_CHAM',
        name: 'Hoàn tất ca chăm sóc',
        color: '#0284c7',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (CARE)',
        systemEventTrigger: 'Bấm [Lưu & Đóng] trên Panel Chăm sóc Lead',
        description: 'Ghi nhận khi tư vấn viên hoàn tất nội dung trao đổi và chọn [Lưu & Đóng] ca chăm sóc',
        leadCount: 54,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-qt-5',
        code: 'GUI_BAO_GIA',
        name: 'Đã gửi lộ trình & Báo giá',
        color: '#ea580c',
        origin: 'custom',
        description: 'Tư vấn viên gửi thông tin học phí, lộ trình đào tạo và ưu đãi qua Zalo/email',
        leadCount: 42,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-tad',
    code: 'TAD',
    name: '[T2] Đánh giá & Học thử',
    phaseGroup: 'T2',
    phaseGroupLabel: 'Đánh giá & Học thử',
    color: '#ec4899',
    order: 3,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 72,
    actionLabel: 'Đặt lịch test / Học thử',
    description: 'Học viên đặt lịch test đầu vào, tham gia học thử và nhận kết quả xếp lớp học thuật',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-tad-1',
        code: 'DA_DAT_TEST',
        name: 'Đã đặt lịch kiểm tra năng lực',
        color: '#f87171',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Tạo phiếu Booking Test',
        leadCount: 68,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-2',
        code: 'VANG_TEST',
        name: 'Vắng test (No-show)',
        color: '#dc2626',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Học viên vắng mặt giờ test',
        requiresNote: true,
        leadCount: 16,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-3',
        code: 'DA_DANG_KY_THU',
        name: 'Đã đăng ký học thử',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lớp học thử (Trial Class)',
        systemEventTrigger: 'Tạo lịch học thử',
        leadCount: 38,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-4',
        code: 'CHUA_GIAO_GV',
        name: 'Chưa phân công giáo viên test',
        color: '#a855f7',
        origin: 'custom',
        leadCount: 12,
        isActive: true,
      },
      {
        id: 'sub-dtt-1',
        code: 'CHO_GV_CHAM',
        name: 'Chờ giáo viên nhập kết quả',
        color: '#880e4f',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Học viên hoàn thành bài test',
        leadCount: 22,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dtt-2',
        code: 'HOAN_TAT_THU',
        name: 'Hoàn tất buổi học thử',
        color: '#9333ea',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lớp học thử (Trial Class)',
        systemEventTrigger: 'Điểm danh có mặt lớp học thử',
        leadCount: 29,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-1',
        code: 'DAT_SUPERKIDS',
        name: 'Đạt trình độ SuperKids',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level SuperKids',
        leadCount: 45,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-2',
        code: 'DAT_FLYERS',
        name: 'Đạt trình độ Flyers',
        color: '#d946ef',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level Flyers',
        leadCount: 32,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-3',
        code: 'DAT_KINDY',
        name: 'Đạt trình độ Kindy Mầm non',
        color: '#a855f7',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level Kindy',
        leadCount: 18,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-4',
        code: 'CHO_PH_XAC_NHAN',
        name: 'Chờ phụ huynh duyệt lộ trình',
        color: '#6366f1',
        origin: 'custom',
        leadCount: 28,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-dentt',
    code: 'DENTT',
    name: '[T3] Xác nhận nhập học (Chờ chốt deal)',
    phaseGroup: 'T3',
    phaseGroupLabel: 'Chốt Deal & Nhập học',
    color: '#0d9488',
    order: 4,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 48,
    actionLabel: 'Xác nhận nộp phí / Đặt cọc',
    description: 'Phụ huynh đồng ý ghi danh, hẹn nộp tiền mặt, chờ chuyển khoản hoặc cọc giữ chỗ',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-dentt-1',
        code: 'HEN_NOP_TIEN_MAT',
        name: 'Hẹn nộp tiền mặt tại cơ sở',
        color: '#059669',
        origin: 'custom',
        leadCount: 34,
        suggestsCallback: true,
        description: 'Phụ huynh hẹn ngày giờ đến trung tâm/cơ sở để nộp tiền mặt hoặc quẹt thẻ POS',
        isActive: true,
      },
      {
        id: 'sub-dentt-2',
        code: 'CHO_CHUYEN_KHOAN',
        name: 'Chờ chuyển khoản học phí',
        color: '#0284c7',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Chọn phương thức chuyển khoản',
        leadCount: 26,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dentt-3',
        code: 'DA_THU_COC',
        name: 'Đã cọc học phí (50%)',
        color: '#0d9488',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Xác nhận phiếu thu cọc',
        leadCount: 21,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dentt-4',
        code: 'GIU_CHO_24H',
        name: 'Giữ chỗ ưu đãi trong 24h',
        color: '#eab308',
        origin: 'custom',
        leadCount: 15,
        suggestsCallback: true,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-order',
    code: 'T4',
    name: '[T4] Thực hiện đơn & Bàn giao',
    phaseGroup: 'T4',
    phaseGroupLabel: 'Bàn giao & Xếp lớp',
    color: '#f97316',
    order: 5,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 48,
    actionLabel: 'Chuyển giao buổi & Giao giáo trình',
    description: 'Đơn hàng được lập: Chuyển giao số buổi học sang Xếp lớp (/app/class_placement) và Bàn giao giáo trình/học liệu tại quầy hoặc giao tận nơi (/app/order_fulfillment)',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-t4-cgh',
        code: 'CHO_BAN_GIAO',
        name: 'Chờ bàn giao giáo trình',
        color: '#f97316',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Tạo phiếu xuất bàn giao sách giáo trình / học liệu',
        description: 'Đơn hàng phát sinh giáo trình/học liệu, chờ chuẩn bị để giao cho học sinh tại cơ sở hoặc gửi tận nơi',
        leadCount: 28,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-dgh',
        code: 'DANG_GIAO_HANG',
        name: 'Đang giao hàng tận nơi',
        color: '#eab308',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Xuất kho và bắt đầu giao giáo trình tận nơi',
        description: 'Giáo trình, học liệu đang được giao đến địa chỉ nhà học sinh theo yêu cầu',
        leadCount: 19,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-gtc',
        code: 'DA_BAN_GIAO',
        name: 'Đã bàn giao giáo trình / học liệu',
        color: '#10b981',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Xác nhận bàn giao tại cơ sở hoặc giao tận nơi thành công',
        description: 'Học sinh/phụ huynh đã nhận đủ sách giáo trình, học liệu và quà tặng',
        leadCount: 45,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-cxl',
        code: 'CHO_XEP_LOP',
        name: 'Chờ xếp lớp đào tạo',
        color: '#0284c7',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Xếp lớp (Class Placement)',
        systemEventTrigger: 'Đơn hàng được lập, kích hoạt chuyển giao số buổi học',
        description: 'Học sinh đã được cấp quota buổi học từ đơn hàng, chờ bố trí lịch học và phòng học',
        leadCount: 36,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-dxl',
        code: 'DA_XEP_LOP',
        name: 'Đã xếp lớp chính thức',
        color: '#059669',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Xếp lớp (Class Placement)',
        systemEventTrigger: 'Gán học viên vào lớp học thành công',
        description: 'Hoàn tất phân bổ học viên vào lớp học, chuẩn bị bước vào buổi học đầu tiên',
        leadCount: 42,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-t-datt1p',
        code: 'T_DATT1P',
        name: 'Thanh toán 1 phần (Còn công nợ)',
        color: '#f43f5e',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Xác nhận phiếu thu đợt 1, ghi nhận công nợ còn lại',
        description: 'Đã thu tiền đợt 1, trung tâm tiếp tục theo dõi thu nốt khoản phí còn lại',
        leadCount: 14,
        isActive: true,
        isSystemCore: true,
      },
      // Các nhãn sự cố / hoàn trả rẽ nhánh xuống khối ngoại lệ bên dưới
      {
        id: 'sub-t4-cdh',
        code: 'CDH',
        name: 'Chờ duyệt đổi / hoàn sách',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 4,
        description: 'Phụ huynh yêu cầu đổi cấp độ giáo trình hoặc hoàn trả học cụ',
        isActive: true,
      },
      {
        id: 'sub-t4-danghh',
        code: 'DANG_HOAN',
        name: 'Đang xử lý thu hồi',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Tiếp nhận yêu cầu thu hồi học liệu',
        leadCount: 3,
        description: 'Đang làm thủ tục nhận lại giáo trình, học cụ về kho cơ sở',
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-dahh',
        code: 'DA_HOAN_TRA',
        name: 'Đã thu hồi / Hoàn trả',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Kho cơ sở xác nhận nhập lại học cụ',
        leadCount: 5,
        description: 'Đã nhập kho lại sách giáo trình và điều chỉnh trên đơn hàng',
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t4-tl',
        code: 'HUY_DON_HANG',
        name: 'Hủy đơn hàng chưa thực hiện',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Hủy đơn hàng chưa kích hoạt dịch vụ',
        requiresNote: true,
        leadCount: 2,
        description: 'Hủy đơn hàng và hoàn hủy số buổi học chưa phát sinh buổi học nào',
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-won',
    code: 'T5',
    name: '[T5] Hoàn tất & Thành công (Won)',
    phaseGroup: 'T5',
    phaseGroupLabel: 'Thành công',
    color: '#10b981',
    order: 6,
    stageType: 'won',
    isSystemCore: true,
    actionLabel: 'Theo dõi học tập chính thức',
    description: 'Đã hoàn tất thanh toán học phí, nhận đủ giáo trình/học liệu và chính thức tham gia học tập tại trung tâm',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-t5-dnbank',
        code: 'DA_THU_DU',
        name: 'Đã thu đủ 100% học phí',
        color: '#10b981',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Xác nhận thu đủ học phí theo đơn hàng',
        description: 'Phiếu thu hoàn tất, đơn hàng không còn công nợ',
        leadCount: 88,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t5-t-tc',
        code: 'DANG_HOC_CHINH_THUC',
        name: 'Đang học chính thức',
        color: '#059669',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Xếp lớp & Đào tạo',
        systemEventTrigger: 'Học viên có mặt điểm danh buổi học đầu tiên',
        description: 'Đã chuyển đổi thành công từ Lead thành Học viên chính thức (/app/students)',
        leadCount: 110,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t5-t-tc1p',
        code: 'HOAN_TAT_BAN_GIAO',
        name: 'Hoàn tất bàn giao & Nhập học',
        color: '#0d9488',
        origin: 'system',
        systemModule: 'order_fulfillment',
        systemModuleLabel: 'Bàn giao & Giao hàng',
        systemEventTrigger: 'Ký nhận đủ giáo trình và vào lớp học',
        description: 'Học viên nhận đủ học liệu và đã sẵn sàng cho toàn bộ khóa học',
        leadCount: 64,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-lost',
    code: 'LOST',
    name: 'Thất bại & Dừng chăm sóc (Lost)',
    phaseGroup: 'terminal',
    phaseGroupLabel: 'Dừng chăm sóc',
    color: '#64748b',
    order: 7,
    stageType: 'global_lost',
    isSystemCore: true,
    actionLabel: 'Chuyển Kho Ủ ấm / DNC',
    description: 'Phụ huynh từ chối đăng ký, chuyển vào kho ủ ấm lưu trữ kèm lý do chi tiết',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-fail-1',
        code: 'CHE_PHI_CAO',
        name: 'Chê học phí cao',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 84,
        description: 'Không đủ ngân sách hoặc so sánh giá',
        isActive: true,
      },
      {
        id: 'sub-fail-2',
        code: 'NHA_XA',
        name: 'Nhà xa cơ sở / Không tiện đưa đón',
        color: '#f97316',
        origin: 'custom',
        leadCount: 62,
        isActive: true,
      },
      {
        id: 'sub-fail-3',
        code: 'HOC_CHO_KHAC',
        name: 'Đã chọn trung tâm khác',
        color: '#e11d48',
        origin: 'custom',
        requiresNote: true,
        leadCount: 48,
        isActive: true,
      },
      {
        id: 'sub-fail-4',
        code: 'KHONG_LIEN_LAC_DUOC',
        name: 'Không liên lạc được (>5 lần gọi)',
        color: '#64748b',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Tổng đài & Cuộc gọi',
        systemEventTrigger: 'Vượt ngưỡng tối đa số lần gọi không nghe',
        leadCount: 39,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-thua-1',
        code: 'DTT_GIA_RE',
        name: 'Đối thủ học phí rẻ hơn',
        color: '#475569',
        origin: 'custom',
        requiresNote: true,
        leadCount: 28,
        isActive: true,
      },
      {
        id: 'sub-thua-2',
        code: 'DTT_GAN_NHA',
        name: 'Đối thủ gần nhà hơn',
        color: '#334155',
        origin: 'custom',
        leadCount: 19,
        isActive: true,
      },
      {
        id: 'sub-klp-1',
        code: 'CHAN_CUOC_GOI',
        name: 'Yêu cầu không làm phiền / Chặn gọi',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 14,
        isActive: true,
      },
      {
        id: 'sub-huy-1',
        code: 'HUY_KE_HOACH',
        name: 'Thay đổi kế hoạch gia đình',
        color: '#94a3b8',
        origin: 'custom',
        leadCount: 22,
        isActive: true,
      },
      {
        id: 'sub-huy-2',
        code: 'CHUYEN_NHA',
        name: 'Chuyển chỗ ở / Đi tỉnh',
        color: '#64748b',
        origin: 'custom',
        leadCount: 15,
        isActive: true,
      },
    ],
  },
]

export const MOCK_PIPELINE_STAGES_POOL_M: PipelineStageConfig[] = [
  {
    id: 'stage-m-0',
    code: 'M0',
    name: '[M0] Tiếp nhận Lead Marketing',
    phaseGroup: 'M0',
    phaseGroupLabel: 'Tiếp nhận Lead Marketing',
    color: '#38bdf8',
    order: 1,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 6,
    actionLabel: 'Sàng lọc dữ liệu form mới',
    description: 'Data mới đổ về từ Landing Page, Facebook Lead Form, TikTok Ads; bot tự động gửi tin nhắn chào mừng',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-m0-1',
        code: 'FORM_LANDING_PAGE',
        name: 'Form Landing Page mới',
        color: '#64c8f5',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Tiếp nhận Marketing',
        systemEventTrigger: 'Phụ huynh điền form landing page',
        leadCount: 850,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m0-2',
        code: 'FORM_FB_TIKTOK',
        name: 'Form FB / TikTok Ads',
        color: '#38bdf8',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Tiếp nhận Marketing',
        systemEventTrigger: 'Lead từ chiến dịch quảng cáo mạng xã hội',
        leadCount: 620,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m0-3',
        code: 'BOT_ZNS_CHAO_MUNG',
        name: 'Tự động gửi Zalo ZNS chào mừng',
        color: '#0ea5e9',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (CARE)',
        systemEventTrigger: 'Hệ thống tự động kích hoạt gửi tin nhắn ZNS',
        leadCount: 420,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m0-4',
        code: 'SO_AO_SPAM',
        name: 'Số ảo / Thiếu số / Spam',
        color: '#64748b',
        origin: 'custom',
        leadCount: 65,
        requiresNote: true,
        description: 'Số điện thoại không đủ 10 số hoặc điền thông tin rác',
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-m-1',
    code: 'M1',
    name: '[M1] Thẩm định & Phân loại',
    phaseGroup: 'M1',
    phaseGroupLabel: 'Thẩm định & Phân loại',
    color: '#f59e0b',
    order: 2,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 24,
    actionLabel: 'Xác định nhu cầu & Độ tuổi',
    description: 'Marketing kiểm tra sơ bộ chất lượng lead, kiểm tra độ tuổi học sinh và chương trình học quan tâm',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-m1-1',
        code: 'DUNG_DO_TUOI',
        name: 'Đúng độ tuổi tuyển sinh (4-15 tuổi)',
        color: '#fbbf24',
        origin: 'custom',
        leadCount: 310,
        isActive: true,
      },
      {
        id: 'sub-m1-2',
        code: 'QUAN_TAM_HE',
        name: 'Quan tâm Trại hè & Khóa Hè',
        color: '#f59e0b',
        origin: 'custom',
        leadCount: 220,
        isActive: true,
      },
      {
        id: 'sub-m1-3',
        code: 'CAN_NHAC_NGAN_SACH',
        name: 'Đang cân nhắc mức ngân sách',
        color: '#d97706',
        origin: 'custom',
        leadCount: 180,
        isActive: true,
      },
      {
        id: 'sub-m1-4',
        code: 'HEN_GOI_LAI_M',
        name: 'Hẹn gọi lại thẩm định sau',
        color: '#ea580c',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Lead (Lịch hẹn)',
        suggestsCallback: true,
        leadCount: 95,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-m-2',
    code: 'M2',
    name: '[M2] Đạt Chuẩn - Chuyển Bàn Giao',
    phaseGroup: 'M2',
    phaseGroupLabel: 'Bàn giao Tuyển sinh',
    color: '#ec4899',
    order: 3,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 12,
    actionLabel: 'Bàn giao sang Kho Telesales',
    description: 'Lead đạt tiêu chuẩn (MQL) được phân bổ về chi nhánh gần nhất và đồng bộ sang Kho Telesales để gọi chốt',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-m2-1',
        code: 'MQL_CHO_SALE_NHAN',
        name: 'Đạt chuẩn MQL - Chờ Telesale nhận',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Phân bổ Lead',
        systemEventTrigger: 'Marketing duyệt đạt chuẩn MQL',
        leadCount: 140,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m2-2',
        code: 'GAN_CO_SO_GAN_NHAT',
        name: 'Định tuyến cơ sở gần phụ huynh',
        color: '#db2777',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Định tuyến Chi nhánh',
        systemEventTrigger: 'Tự động gán cơ sở theo vị trí phụ huynh',
        leadCount: 110,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m2-3',
        code: 'DA_DONG_BO_KHO_T',
        name: 'Đã đồng bộ sang Kho Telesales',
        color: '#be185d',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Đồng bộ Kho',
        systemEventTrigger: 'Chuyển dữ liệu vào Kho T (/app/crm_leads)',
        leadCount: 85,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-m-3',
    code: 'M3',
    name: '[M3] Nuôi dưỡng Dài hạn (Nurture)',
    phaseGroup: 'M3',
    phaseGroupLabel: 'Nuôi dưỡng Marketing',
    color: '#8b5cf6',
    order: 4,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 168,
    actionLabel: 'Kích hoạt chiến dịch nuôi dưỡng',
    description: 'Phụ huynh chưa có nhu cầu học ngay hoặc chờ kỳ sau; đưa vào danh sách gửi tài liệu học thuật và cẩm nang',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-m3-1',
        code: 'NHAN_TAI_LIEU_HOC',
        name: 'Đăng ký nhận tài liệu học tập',
        color: '#a78bfa',
        origin: 'custom',
        leadCount: 160,
        isActive: true,
      },
      {
        id: 'sub-m3-2',
        code: 'CHO_KY_MOI',
        name: 'Chờ kỳ tuyển sinh mới / Năm học mới',
        color: '#8b5cf6',
        origin: 'custom',
        leadCount: 120,
        isActive: true,
      },
      {
        id: 'sub-m3-3',
        code: 'CHUOI_EMAIL_NURTURE',
        name: 'Theo dõi chuỗi Email / ZNS Nurture',
        color: '#7c3aed',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Chăm sóc Tự động (CARE)',
        systemEventTrigger: 'Kích hoạt kịch bản chăm sóc nuôi dưỡng dài hạn',
        leadCount: 90,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-m-4',
    code: 'M4',
    name: '[M4] Hoàn tất Bàn giao Marketing',
    phaseGroup: 'M4',
    phaseGroupLabel: 'Hoàn tất Bàn giao',
    color: '#10b981',
    order: 5,
    stageType: 'won',
    isSystemCore: true,
    actionLabel: 'Ghi nhận chuyển đổi Marketing',
    description: 'Lead đã được Telesales kết nối thành công và phát sinh lịch hẹn trải nghiệm hoặc đơn hàng',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-m4-1',
        code: 'BAN_GIAO_THANH_CONG',
        name: 'Đã bàn giao Telesales thành công',
        color: '#10b981',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Tiếp nhận Kho T',
        systemEventTrigger: 'Telesale tiếp nhận và phát sinh cuộc gọi',
        leadCount: 450,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-m4-2',
        code: 'DEN_CO_SO_TRUC_TIEP',
        name: 'Đã đến tham quan cơ sở trực tiếp',
        color: '#059669',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Trải nghiệm Cơ sở',
        systemEventTrigger: 'Phụ huynh check-in tại quầy lễ tân',
        leadCount: 180,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-m-lost',
    code: 'M_LOST',
    name: 'Rác & Hủy sàng lọc Marketing',
    phaseGroup: 'terminal',
    phaseGroupLabel: 'Hủy Marketing',
    color: '#64748b',
    order: 6,
    stageType: 'global_lost',
    isSystemCore: true,
    actionLabel: 'Chuyển Kho Data Rác',
    description: 'Data không liên lạc được, số ảo hoặc phụ huynh khiếu nại không đăng ký thông tin',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-mlost-1',
        code: 'SO_THUE_BAO_KHOA',
        name: 'Số thuê bao khóa / Không tồn tại',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Nhật ký Cuộc gọi',
        systemEventTrigger: 'Telesale ghi nhận số không liên lạc được',
        leadCount: 112,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-mlost-2',
        code: 'TRUNG_SO_KHO_KHAC',
        name: 'Trùng SĐT với Kho khác (Deduplicate)',
        color: '#f97316',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Hệ thống Khử trùng',
        systemEventTrigger: 'Trùng lặp số điện thoại với hồ sơ đang chăm sóc',
        leadCount: 78,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-mlost-3',
        code: 'KHONG_NHU_CAU_M',
        name: 'Không có nhu cầu / Điền nhầm',
        color: '#e11d48',
        origin: 'custom',
        requiresNote: true,
        leadCount: 64,
        isActive: true,
      },
      {
        id: 'sub-mlost-4',
        code: 'NGOAI_DO_TUOI',
        name: 'Ngoài độ tuổi tuyển sinh của trung tâm',
        color: '#64748b',
        origin: 'custom',
        leadCount: 45,
        isActive: true,
      },
    ],
  },
]

export const MOCK_PIPELINE_STAGES_POOL_C: PipelineStageConfig[] = [
  {
    id: 'stage-c-0',
    code: 'CC0',
    name: '[CC0] Danh sách Tiếp nhận Tái phí',
    phaseGroup: 'CC0',
    phaseGroupLabel: 'Tiếp nhận Tái phí',
    color: '#38bdf8',
    order: 1,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 24,
    actionLabel: 'Sàng lọc danh sách sắp hết hạn',
    description: 'Học viên còn dưới 8 buổi hoặc bảo lưu đến hạn; hệ thống tự động cảnh báo phân bổ cho chuyên viên CSKH',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-c0-1',
        code: 'SAP_HET_KHOA_30D',
        name: 'Sắp hết khóa trong 30 ngày (<8 buổi)',
        color: '#64c8f5',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Cảnh báo Tái phí (CARE)',
        systemEventTrigger: 'Học viên còn dưới 8 buổi học theo giáo trình',
        leadCount: 210,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c0-2',
        code: 'BAO_LUU_DEN_HAN',
        name: 'Bảo lưu đến hạn kích hoạt lại',
        color: '#38bdf8',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Bảo lưu & Tái tục',
        systemEventTrigger: 'Hết thời hạn bảo lưu theo biên bản',
        leadCount: 65,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c0-3',
        code: 'NGUY_CO_DUNG_HOC',
        name: 'Nguy cơ dừng học (Nghỉ >3 buổi)',
        color: '#f43f5e',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Cảnh báo Học vụ',
        systemEventTrigger: 'Học viên nghỉ học liên tiếp 3 buổi',
        leadCount: 45,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-c-1',
    code: 'CC1',
    name: '[CC1] Khảo sát & Tư vấn Khóa Nâng cao',
    phaseGroup: 'CC1',
    phaseGroupLabel: 'Tư vấn Khóa Nâng cao',
    color: '#f59e0b',
    order: 2,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 48,
    actionLabel: 'Khảo sát chất lượng & Gửi lộ trình',
    description: 'Chuyên viên CSKH trao đổi đánh giá kết quả học kỳ, lắng nghe ý kiến phụ huynh và đề xuất lộ trình khóa nâng cao tiếp theo',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-c1-1',
        code: 'KHAO_SAT_HAI_LONG',
        name: 'Khảo sát hài lòng kết quả khóa học',
        color: '#fbbf24',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Đánh giá Khách hàng',
        systemEventTrigger: 'Hoàn tất biểu mẫu khảo sát chất lượng',
        leadCount: 140,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c1-2',
        code: 'DA_TU_VAN_LEVEL_MOI',
        name: 'Đã tư vấn lộ trình Level tiếp theo',
        color: '#f59e0b',
        origin: 'custom',
        leadCount: 115,
        isActive: true,
      },
      {
        id: 'sub-c1-3',
        code: 'UU_DAI_HOC_VIEN_CU',
        name: 'Đề xuất ưu đãi tái phí cho học viên cũ',
        color: '#d97706',
        origin: 'custom',
        leadCount: 80,
        isActive: true,
      },
      {
        id: 'sub-c1-4',
        code: 'HEN_SAU_KY_THI',
        name: 'Hẹn phản hồi sau kỳ thi học kỳ',
        color: '#ea580c',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Lịch hẹn Chăm sóc',
        suggestsCallback: true,
        leadCount: 55,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-c-2',
    code: 'CC2',
    name: '[CC2] Đặt chỗ & Chờ Thanh toán Tái phí',
    phaseGroup: 'CC2',
    phaseGroupLabel: 'Giữ chỗ & Đặt cọc',
    color: '#ec4899',
    order: 3,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 72,
    actionLabel: 'Giữ chỗ & Xuất phiếu thu',
    description: 'Phụ huynh đồng ý cho con học tiếp, chọn lịch học khóa mới và chuyển khoản đặt cọc giữ chỗ',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-c2-1',
        code: 'GIU_CHO_LOP_MOI',
        name: 'Đã chọn lớp & Giữ chỗ khóa mới',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Xếp lớp & Giữ chỗ',
        systemEventTrigger: 'Tạo suất giữ chỗ trên danh sách lớp mới',
        leadCount: 90,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c2-2',
        code: 'DA_DAT_COC_TAI_PHI',
        name: 'Đã đặt cọc tái phí một phần',
        color: '#db2777',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu tiền cọc',
        systemEventTrigger: 'Xác nhận phiếu thu tiền cọc tái phí',
        leadCount: 60,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c2-3',
        code: 'CHO_DUYET_COMBO',
        name: 'Chờ duyệt ưu đãi combo anh em ruột',
        color: '#be185d',
        origin: 'custom',
        requiresNote: true,
        leadCount: 35,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-c-3',
    code: 'CC3',
    name: '[CC3] Hoàn tất Tái phí Thành công',
    phaseGroup: 'CC3',
    phaseGroupLabel: 'Hoàn tất Tái phí',
    color: '#10b981',
    order: 4,
    stageType: 'won',
    isSystemCore: true,
    actionLabel: 'Ghi nhận gia hạn khóa học',
    description: 'Đã hoàn tất thanh toán 100% học phí tái tục, học viên chính thức chuyển tiếp sang khóa học kế tiếp',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-c3-1',
        code: 'THU_DU_TAI_PHI',
        name: 'Đã thu đủ 100% học phí tái tục',
        color: '#10b981',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân Tái phí',
        systemEventTrigger: 'Phiếu thu học phí mới hoàn tất',
        leadCount: 320,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-c3-2',
        code: 'CHINH_THUC_VAO_KHOA',
        name: 'Đã xếp lớp chính thức khóa mới',
        color: '#059669',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Học vụ Khóa mới',
        systemEventTrigger: 'Điểm danh buổi học đầu tiên của khóa mới',
        leadCount: 280,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-c-lost',
    code: 'CC_LOST',
    name: 'Dừng học & Rời bỏ (Dropout)',
    phaseGroup: 'terminal',
    phaseGroupLabel: 'Dừng học',
    color: '#64748b',
    order: 5,
    stageType: 'global_lost',
    isSystemCore: true,
    actionLabel: 'Lưu trữ hồ sơ hoàn thành khóa',
    description: 'Học viên không tiếp tục khóa học; lưu trữ hồ sơ kèm nguyên nhân rời bỏ phục vụ phân tích chất lượng',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-clost-1',
        code: 'HET_CAP_HOC',
        name: 'Đã hoàn thành hết cấp học tại trung tâm',
        color: '#64748b',
        origin: 'custom',
        leadCount: 85,
        isActive: true,
      },
      {
        id: 'sub-clost-2',
        code: 'CHUYEN_TRUONG_NHA',
        name: 'Chuyển trường / Chuyển nơi ở xa',
        color: '#f97316',
        origin: 'custom',
        leadCount: 54,
        isActive: true,
      },
      {
        id: 'sub-clost-3',
        code: 'PHAN_NAN_CHAT_LUONG',
        name: 'Không hài lòng tiến bộ / Phàn nàn',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 32,
        isActive: true,
      },
      {
        id: 'sub-clost-4',
        code: 'AP_LUC_TAI_CHINH',
        name: 'Áp lực tài chính gia đình',
        color: '#e11d48',
        origin: 'custom',
        requiresNote: true,
        leadCount: 28,
        isActive: true,
      },
    ],
  },
]

export const MOCK_PIPELINE_STAGES_POOL_G: PipelineStageConfig[] = [
  {
    id: 'stage-g-0',
    code: 'G0',
    name: '[G0] Đăng ký Sự kiện / Giới thiệu',
    phaseGroup: 'G0',
    phaseGroupLabel: 'Đăng ký Tham gia',
    color: '#38bdf8',
    order: 1,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 12,
    actionLabel: 'Tiếp nhận thông tin người giới thiệu',
    description: 'Nhận thông tin phụ huynh đăng ký qua chương trình Giới thiệu bạn bè (Referral) hoặc vé mời Workshop',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-g0-1',
        code: 'PH_GIOI_THIEU',
        name: 'Phụ huynh cũ giới thiệu người quen',
        color: '#64c8f5',
        origin: 'custom',
        leadCount: 150,
        isActive: true,
      },
      {
        id: 'sub-g0-2',
        code: 'DANG_KY_VE_WORKSHOP',
        name: 'Đăng ký vé Workshop cuối tuần',
        color: '#38bdf8',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Vé Mời Sự Kiện',
        systemEventTrigger: 'Phụ huynh quét mã đăng ký vé tham dự',
        leadCount: 180,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g0-3',
        code: 'QUA_MINI_GAME',
        name: 'Nhận vé trải nghiệm từ mini-game',
        color: '#0284c7',
        origin: 'custom',
        leadCount: 60,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-g-1',
    code: 'G1',
    name: '[G1] Xác nhận Tham dự & Giữ chỗ',
    phaseGroup: 'G1',
    phaseGroupLabel: 'Xác nhận Tham dự',
    color: '#f59e0b',
    order: 2,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 24,
    actionLabel: 'Gửi vé QR & Gọi nhắc lịch',
    description: 'Tư vấn viên liên hệ gửi thư mời điện tử kèm mã QR và gọi điện xác nhận phụ huynh sẽ đưa con đến',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-g1-1',
        code: 'DA_GUI_VE_QR',
        name: 'Đã gửi thư mời điện tử & Mã QR',
        color: '#fbbf24',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Gửi Vé Mời (ZNS)',
        systemEventTrigger: 'Tự động gửi vé mời và lộ trình đi qua Zalo',
        leadCount: 130,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g1-2',
        code: 'DA_GOI_XAC_NHAN_MAT',
        name: 'Đã gọi xác nhận chắc chắn có mặt',
        color: '#f59e0b',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Nhắc Lịch Sự Kiện',
        systemEventTrigger: 'Hoàn tất cuộc gọi xác nhận tham dự',
        leadCount: 110,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g1-3',
        code: 'HEN_WORKSHOP_KE',
        name: 'Hẹn chuyển sang Workshop đợt sau',
        color: '#d97706',
        origin: 'custom',
        suggestsCallback: true,
        leadCount: 35,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-g-2',
    code: 'G2',
    name: '[G2] Check-in & Tham dự Workshop',
    phaseGroup: 'G2',
    phaseGroupLabel: 'Tham gia Sự kiện',
    color: '#ec4899',
    order: 3,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 48,
    actionLabel: 'Quét mã check-in & Vào phòng trải nghiệm',
    description: 'Học sinh và phụ huynh đến trực tiếp cơ sở, check-in nhận quà và tham gia lớp học thử tương tác cùng giáo viên bản ngữ',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-g2-1',
        code: 'CHECKIN_TAI_CO_SO',
        name: 'Đã check-in tham gia Workshop',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lễ tân & Check-in',
        systemEventTrigger: 'Quét mã QR check-in tại quầy lễ tân',
        leadCount: 95,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g2-2',
        code: 'TRAI_NGHIEM_LOP_MAU',
        name: 'Tham gia lớp học thử tương tác',
        color: '#db2777',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lớp Học Trải Nghiệm',
        systemEventTrigger: 'Điểm danh có mặt trong phòng học mẫu',
        leadCount: 80,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g2-3',
        code: 'VANG_MAT_NGAY_HOI',
        name: 'Vắng mặt ngày hội (No-show)',
        color: '#be185d',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Điểm danh Sự kiện',
        systemEventTrigger: 'Không có tín hiệu check-in trong khung giờ',
        leadCount: 25,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-g-3',
    code: 'G3',
    name: '[G3] Tư vấn Chốt Deal Sau Sự kiện',
    phaseGroup: 'G3',
    phaseGroupLabel: 'Chốt Deal Sự kiện',
    color: '#8b5cf6',
    order: 4,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 48,
    actionLabel: 'Tư vấn ưu đãi đặc quyền trong ngày',
    description: 'Chuyên viên tư vấn gặp trực tiếp phụ huynh sau buổi trải nghiệm, giải đáp thắc mắc và trao voucher giảm giá độc quyền',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-g3-1',
        code: 'VOUCHER_NGAY_HOI',
        name: 'Nhận voucher ưu đãi độc quyền sự kiện',
        color: '#a78bfa',
        origin: 'custom',
        leadCount: 65,
        isActive: true,
      },
      {
        id: 'sub-g3-2',
        code: 'TU_VAN_CHOT_NGAY',
        name: 'Tư vấn gói học phí ưu đãi trong ngày',
        color: '#8b5cf6',
        origin: 'custom',
        leadCount: 45,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-g-4',
    code: 'G4',
    name: '[G4] Chuyển đổi Thành công từ Sự kiện',
    phaseGroup: 'G4',
    phaseGroupLabel: 'Hoàn tất Chuyển đổi',
    color: '#10b981',
    order: 5,
    stageType: 'won',
    isSystemCore: true,
    actionLabel: 'Đăng ký nhập học & Ghi nhận Referral',
    description: 'Phụ huynh đăng ký nhập học chính thức ngay tại ngày hội; kích hoạt phần quà tri ân cho phụ huynh giới thiệu',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-g4-1',
        code: 'DANG_KY_TAI_CHO',
        name: 'Đăng ký nhập học tại chỗ',
        color: '#10b981',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng Sự kiện',
        systemEventTrigger: 'Tạo đơn hàng đăng ký tại ngày hội',
        leadCount: 120,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-g4-2',
        code: 'THUONG_REFERRAL',
        name: 'Ghi nhận thưởng Referral phụ huynh cũ',
        color: '#059669',
        origin: 'system',
        systemModule: 'care',
        systemModuleLabel: 'Tri ân Giới thiệu (CARE)',
        systemEventTrigger: 'Kích hoạt voucher tri ân phụ huynh giới thiệu',
        leadCount: 85,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-g-lost',
    code: 'G_LOST',
    name: 'Vắng mặt & Hủy tham gia',
    phaseGroup: 'terminal',
    phaseGroupLabel: 'Hủy Sự kiện',
    color: '#64748b',
    order: 6,
    stageType: 'global_lost',
    isSystemCore: true,
    actionLabel: 'Chuyển lưu trữ sự kiện',
    description: 'Phụ huynh không đến tham gia hoặc hủy vé mời vào phút chót',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-glost-1',
        code: 'BAN_DOT_XUAT',
        name: 'Bận việc gia đình đột xuất',
        color: '#64748b',
        origin: 'custom',
        leadCount: 42,
        isActive: true,
      },
      {
        id: 'sub-glost-2',
        code: 'KHONG_NGHE_MAY_NHAC',
        name: 'Không nghe máy khi gọi nhắc lịch',
        color: '#f97316',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Nhắc Lịch Sự Kiện',
        leadCount: 35,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-glost-3',
        code: 'KHONG_DUNG_DOI_TUONG',
        name: 'Không phù hợp độ tuổi / Sai đối tượng',
        color: '#ef4444',
        origin: 'custom',
        leadCount: 18,
        isActive: true,
      },
    ],
  },
]

export const MOCK_STAGES_BY_POOL: Record<string, PipelineStageConfig[]> = {
  'pool-t': MOCK_PIPELINE_STAGES_POOL_T,
  'pool-m': MOCK_PIPELINE_STAGES_POOL_M,
  'pool-c': MOCK_PIPELINE_STAGES_POOL_C,
  'pool-g': MOCK_PIPELINE_STAGES_POOL_G,
}

export const MOCK_PIPELINE_STAGES: PipelineStageConfig[] = MOCK_PIPELINE_STAGES_POOL_T

export const MOCK_CALL_DISPOSITIONS: CallDispositionConfig[] = [
  {
    id: 'cd-1',
    code: 'SS',
    name: 'Số sai / Nhầm số',
    category: 'invalid_number',
    categoryLabel: 'Số không hợp lệ',
    color: '#333333',
    triggersCallback: false,
    description: 'Số điện thoại không có thực, thiếu số, hoặc người nghe báo nhầm người',
    isActive: true,
  },
  {
    id: 'cd-2',
    code: 'KNM',
    name: 'Không nghe máy',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#0d47a1',
    triggersCallback: true,
    defaultCallbackMinutes: 180,
    description: 'Đổ chuông nhưng không bắt máy. Hệ thống tự động xếp lịch gọi lại sau 3 tiếng',
    isActive: true,
  },
  {
    id: 'cd-3',
    code: 'GL',
    name: 'Hẹn gọi lại',
    category: 'retry_scheduled',
    categoryLabel: 'Hẹn tương tác lại',
    color: '#ab47bc',
    triggersCallback: true,
    defaultCallbackMinutes: 1440,
    description: 'Phụ huynh đang bận họp/lái xe, yêu cầu gọi lại vào khung giờ hẹn cụ thể',
    isActive: true,
  },
  {
    id: 'cd-4',
    code: 'BUSY',
    name: 'Máy bận / Từ chối cuộc gọi',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#e65100',
    triggersCallback: true,
    defaultCallbackMinutes: 60,
    description: 'Máy bận hoặc phụ huynh chủ động gạt máy. Xếp lịch gọi lại sau 1 tiếng',
    isActive: true,
  },
  {
    id: 'cd-5',
    code: 'UNREACHABLE',
    name: 'Thuê bao / Tắt máy',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#5c6bc0',
    triggersCallback: true,
    defaultCallbackMinutes: 360,
    description: 'Tổng đài báo thuê bao không liên lạc được, ngoài vùng phủ sóng',
    isActive: true,
  },
  {
    id: 'cd-6',
    code: 'CONNECTED',
    name: 'Đã kết nối thành công & Trao đổi',
    category: 'connected',
    categoryLabel: 'Kết nối thành công',
    color: '#2e7d32',
    triggersCallback: false,
    description: 'Tư vấn viên đã trao đổi trực tiếp với phụ huynh về nhu cầu khóa học',
    isActive: true,
  },
]

export const MOCK_LEGACY_MAPPINGS: LegacyMappingItem[] = [
  // Giai đoạn T0
  {
    id: 'map-1',
    legacyPhase: 'T0',
    legacyCode: 'SS',
    legacyName: 'Số sai',
    legacyColor: '#333333',
    canDelete: false,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Số không hợp lệ (SS)',
    modernRationale: 'Tách thành kết quả cuộc gọi; số điện thoại được đưa vào danh sách đen sàng lọc, không tạo Lead rác.',
  },
  {
    id: 'map-2',
    legacyPhase: 'T0',
    legacyCode: 'DL',
    legacyName: 'Kho chung',
    legacyColor: '#5b32a8',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Chung Phân Bổ (KHO_DL)',
    modernRationale: 'Được nâng cấp thành Data Pool trung tâm, phân phối dữ liệu cho đội ngũ qua thuật toán Round-Robin.',
  },
  {
    id: 'map-3',
    legacyPhase: 'T0',
    legacyCode: 'KNEW',
    legacyName: 'Kho NEW',
    legacyColor: '#5b32a8',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Tiếp Nhận Mới (KHO_NEW)',
    modernRationale: 'Nơi gom data thô từ các chiến dịch trực tuyến (Landing Page, Mạng xã hội) trước khi tự động kiểm tra trùng.',
  },
  {
    id: 'map-4',
    legacyPhase: 'T0',
    legacyCode: 'CL',
    legacyName: 'Kho lọc',
    legacyColor: '#795548',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Sàng Lọc & Tái Khai Thác (KHO_R)',
    modernRationale: 'Kho chứa các liên hệ bị thu hồi do quá hạn xử lý (SLA) hoặc các cơ hội cũ cần ủ ấm 60-90 ngày.',
  },

  // Giai đoạn T1
  {
    id: 'map-5',
    legacyPhase: 'T1',
    legacyCode: 'NEW',
    legacyName: 'New',
    legacyColor: '#64c8f5',
    canDelete: false,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Mới tiếp nhận (NEW)',
    modernRationale: 'Bước mở đầu của hành trình tuyển sinh sau khi Lead được gán cho tư vấn viên phụ trách.',
  },
  {
    id: 'map-6',
    legacyPhase: 'T1',
    legacyCode: 'KNM',
    legacyName: 'KNM',
    legacyColor: '#0d47a1',
    canDelete: false,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Không nghe máy (KNM)',
    modernRationale: 'Lưu vào lịch sử cuộc gọi với bộ đếm số lần gọi; Lead vẫn giữ nguyên trạng thái tư vấn.',
  },
  {
    id: 'map-7',
    legacyPhase: 'T1',
    legacyCode: 'GL',
    legacyName: 'GL',
    legacyColor: '#ab47bc',
    canDelete: true,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Hẹn gọi lại (GL)',
    modernRationale: 'Lưu thành lịch hẹn tương tác kèm thời gian nhắc nhở tự động trên bảng điều khiển của nhân sự.',
  },
  {
    id: 'map-8',
    legacyPhase: 'T1',
    legacyCode: 'QT',
    legacyName: 'Quan tâm',
    legacyColor: '#ff9800',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đang tư vấn (QT)',
    modernRationale: 'Khách hàng có nhu cầu học tập rõ ràng, đang thảo luận chương trình học và thời gian học.',
  },
  {
    id: 'map-9',
    legacyPhase: 'T1',
    legacyCode: 'TAD',
    legacyName: 'Test/Demo',
    legacyColor: '#e57373',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Hẹn Kiểm tra / Trải nghiệm (TAD)',
    modernRationale: 'Tự động liên kết và mở phiếu đặt lịch tại phân hệ Kiểm tra năng lực (/app/booking_test).',
  },
  {
    id: 'map-10',
    legacyPhase: 'T1',
    legacyCode: 'DTT',
    legacyName: 'Đã Test /Demo',
    legacyColor: '#880e4f',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đã tham gia Test / Demo (DTT)',
    modernRationale: 'Ghi nhận sự có mặt của học viên tại buổi đánh giá hoặc lớp học thử (/app/trial_class).',
  },
  {
    id: 'map-11',
    legacyPhase: 'T1',
    legacyCode: 'TLTTT',
    legacyName: 'Ra level',
    legacyColor: '#f48fb1',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đã có kết quả xếp lớp (TLTTT)',
    modernRationale: 'Giáo viên/Chuyên môn hoàn tất phiếu chấm điểm năng lực và đề xuất trình độ khóa học tương ứng.',
  },
  {
    id: 'map-12',
    legacyPhase: 'T1',
    legacyCode: 'DENTT',
    legacyName: 'Confirm',
    legacyColor: '#00897b',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Chờ chốt deal (DENTT)',
    modernRationale: 'Phụ huynh đồng ý phương án đào tạo, chuyển sang giai đoạn tạo đơn hàng và chọn hình thức thu phí.',
  },
  {
    id: 'map-13',
    legacyPhase: 'T1',
    legacyCode: 'DADENTT',
    legacyName: 'Đã đến TT',
    legacyColor: '#00bcd4',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Lịch sử Sự kiện: Check-in tại Cơ sở',
    modernRationale: 'Là một mốc sự kiện điểm danh tại quầy tiếp đón/lễ tân, không đóng vai trò làm trạng thái phễu.',
  },
  {
    id: 'map-14',
    legacyPhase: 'T1',
    legacyCode: 'SDT',
    legacyName: 'Tiềm năng',
    legacyColor: '#f44336',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Thuộc tính Lead: Độ ưu tiên cao (Hot Lead)',
    modernRationale: 'Chuyển thành huy hiệu cờ đánh giá tiềm năng cao trên dòng thông tin của Lead.',
  },

  // Giai đoạn T2
  {
    id: 'map-15',
    legacyPhase: 'T2',
    legacyCode: 'FAIL',
    legacyName: 'Fail',
    legacyColor: '#9e9e9e',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Thất bại - Không chuyển đổi',
    modernRationale: 'Trạng thái kết thúc thất bại toàn cục (Global Lost), bắt buộc chọn lý do: Giá cao, Chưa phù hợp thời gian...',
  },
  {
    id: 'map-16',
    legacyPhase: 'T2',
    legacyCode: 'THUA',
    legacyName: 'Thua',
    legacyColor: '#37474f',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Thua đối thủ cạnh tranh',
    modernRationale: 'Trạng thái kết thúc thất bại để phục vụ báo cáo phân tích đối thủ cạnh tranh trên địa bàn.',
  },
  {
    id: 'map-17',
    legacyPhase: 'T2',
    legacyCode: 'KLP',
    legacyName: 'Ko Lphiền',
    legacyColor: '#546e7a',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Cờ Hồ sơ: Danh sách Không làm phiền (DNC)',
    modernRationale: 'Đánh dấu hồ sơ vào danh sách đen không gọi, tự động chặn mọi chiến dịch liên hệ tiếp theo.',
  },
  {
    id: 'map-18',
    legacyPhase: 'T2',
    legacyCode: 'HUY',
    legacyName: 'Hủy',
    legacyColor: '#9e9e9e',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Khách hủy đăng ký',
    modernRationale: 'Dừng quy trình tuyển sinh khi khách hàng chủ động hủy lịch test hoặc tạm dừng kế hoạch học.',
  },
  {
    id: 'map-19',
    legacyPhase: 'T2',
    legacyCode: 'DG',
    legacyName: 'Đã gộp',
    legacyColor: '#a1887f',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Cơ chế Hồ sơ: Bản ghi đã được Gộp (Merged)',
    modernRationale: 'Dữ liệu được hợp nhất vào hồ sơ chính thông qua công cụ giải quyết trùng lặp (Deduplication).',
  },

  // Giai đoạn T3
  {
    id: 'map-20',
    legacyPhase: 'T3',
    legacyCode: 'BANK',
    legacyName: 'Bank',
    legacyColor: '#afb42b',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Phương thức Thanh toán: Chuyển khoản (Bank Transfer)',
    modernRationale: 'Thuộc tính hình thức thanh toán của đơn hàng tại phân hệ Đơn hàng & Phiếu thu (/app/orders).',
  },
  {
    id: 'map-21',
    legacyPhase: 'T3',
    legacyCode: 'COD',
    legacyName: 'COD',
    legacyColor: '#2e7d32',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Phương thức Thanh toán: Thu tiền khi nhận (COD)',
    modernRationale: 'Áp dụng cho đơn hàng có kèm bộ học liệu/giáo trình vật lý giao đến tận nhà.',
  },
  {
    id: 'map-22',
    legacyPhase: 'T3',
    legacyCode: 'CGH',
    legacyName: 'Chờ giao hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Chờ đóng gói & Bàn giao',
    modernRationale: 'Chuyển vào phân hệ Bàn giao & Giao hàng (/app/order_fulfillment), thủ kho xử lý đóng gói.',
  },
  {
    id: 'map-23',
    legacyPhase: 'T3',
    legacyCode: 'DGNVC',
    legacyName: 'Đã gửi NVC',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã bàn giao Đơn vị Vận chuyển',
    modernRationale: 'Đã có mã vận đơn từ bưu điện (ViettelPost, GHTK, GHN), đang chờ hãng vận chuyển tiếp nhận.',
  },
  {
    id: 'map-24',
    legacyPhase: 'T3',
    legacyCode: 'DGH',
    legacyName: 'Đang giao hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đang phát hàng (In Transit)',
    modernRationale: 'Shipper đang trên đường giao bưu phẩm sách/học liệu đến địa chỉ của học viên.',
  },
  {
    id: 'map-25',
    legacyPhase: 'T3',
    legacyCode: 'GTC',
    legacyName: 'Giao thành công',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Giao hàng thành công',
    modernRationale: 'Bưu phẩm đã đến tay phụ huynh, xác nhận hoàn tất khâu giao tài liệu đào tạo.',
  },
  {
    id: 'map-26',
    legacyPhase: 'T3',
    legacyCode: 'CDH',
    legacyName: 'Chờ duyệt hoàn',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Chờ duyệt hoàn hàng',
    modernRationale: 'Giao không thành công sau 3 lần gọi, bưu điện gửi yêu cầu phê duyệt chuyển hoàn.',
  },

  // Giai đoạn T4
  {
    id: 'map-27',
    legacyPhase: 'T4',
    legacyCode: 'DDH',
    legacyName: 'Đã duyệt hoàn',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã duyệt hoàn',
    modernRationale: 'Quản lý vận hành xác nhận đồng ý cho bưu kiện quay đầu về kho sách trung tâm.',
  },
  {
    id: 'map-28',
    legacyPhase: 'T4',
    legacyCode: 'DANGHH',
    legacyName: 'Đang hoàn hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đang quay đầu hoàn kho',
    modernRationale: 'Bưu điện đang luân chuyển gói học liệu về lại cơ sở lưu kho ban đầu.',
  },
  {
    id: 'map-29',
    legacyPhase: 'T4',
    legacyCode: 'DAHH',
    legacyName: 'Đã hoàn hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã nhập kho hoàn',
    modernRationale: 'Thủ kho nhận lại sách và hoàn trả số lượng vào tồn kho giáo trình.',
  },
  {
    id: 'map-30',
    legacyPhase: 'T4',
    legacyCode: 'TL',
    legacyName: 'Thất lạc',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Bưu kiện thất lạc',
    modernRationale: 'Ghi nhận sự cố vận chuyển để lập hồ sơ bồi thường với bên đơn vị chuyển phát.',
  },
  {
    id: 'map-31',
    legacyPhase: 'T4',
    legacyCode: 'DH',
    legacyName: 'Đã hủy',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Đơn hàng: Đã hủy đơn hàng (Order Canceled)',
    modernRationale: 'Đơn hàng mua khóa học bị hủy bỏ, hóa đơn tài chính bị thu hồi.',
  },
  {
    id: 'map-32',
    legacyPhase: 'T4',
    legacyCode: 'T_DATT1',
    legacyName: 'Thanh toán 1 phần',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Trạng thái Thanh toán: Đã cọc / Trả góp đợt 1',
    modernRationale: 'Quản lý công nợ trên đơn hàng, hỗ trợ phụ huynh đóng học phí làm nhiều đợt.',
  },
]
