import {
  DataPoolConfig,
  PipelineStageConfig,
  CallDispositionConfig,
  LegacyMappingItem,
} from './leadLifecycleTypes'

export const MOCK_DATA_POOLS: DataPoolConfig[] = [
  {
    id: 'pool-m',
    code: 'M',
    name: 'Kho M',
    url: 'https://marketing.rinoedu.vn/lead-capture/kho-m',
    leadCount: 2310,
    isActive: true,
  },
  {
    id: 'pool-g',
    code: 'G',
    name: 'Kho G',
    url: 'https://rinoedu.vn/landing/workshop-gioi-thieu',
    leadCount: 450,
    isActive: true,
  },
  {
    id: 'pool-c',
    code: 'C',
    name: 'Kho CC',
    url: 'https://crm.rinoedu.vn/cskh/cham-soc-tai-phi',
    leadCount: 680,
    isActive: true,
  },
  {
    id: 'pool-t',
    code: 'T',
    name: 'Kho T',
    url: 'https://telesales.rinoedu.vn/inbound/lead-t',
    leadCount: 1240,
    isActive: true,
  },
]

export const MOCK_PIPELINE_STAGES: PipelineStageConfig[] = [
  {
    id: 'stage-new',
    code: 'NEW',
    name: '[T0] Tiếp nhận Lead',
    phaseGroup: 'T0',
    phaseGroupLabel: 'Tiếp nhận Lead',
    color: '#38bdf8',
    order: 1,
    stageType: 'in_progress',
    isSystemCore: true,
    slaHours: 12,
    actionLabel: 'Gọi tiếp cận lần đầu',
    description: 'Data mới đổ về từ Kho M, G, CC, T; tư vấn viên sàng lọc và liên hệ ban đầu',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-new-1',
        code: 'CHUA_CO_SALE',
        name: 'Mới về - Chưa phân Sale',
        color: '#64c8f5',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Sàng lọc & Phân bổ',
        systemEventTrigger: 'Data mới đổ về từ Kho',
        leadCount: 145,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-new-2',
        code: 'DA_PHAN_SALE',
        name: 'Đã giao Sale - Chưa gọi',
        color: '#38bdf8',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Phân bổ Lead',
        systemEventTrigger: 'Quản lý gán tư vấn viên',
        leadCount: 88,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-new-3',
        code: 'SO_SAI',
        name: 'Số sai / Spam / Rác',
        color: '#64748b',
        origin: 'custom',
        leadCount: 24,
        requiresNote: true,
        description: 'Số điện thoại ảo hoặc thiếu số',
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-qt',
    code: 'QT',
    name: '[T1] Đang tư vấn & Chăm sóc',
    phaseGroup: 'T1',
    phaseGroupLabel: 'Tư vấn & Chăm sóc',
    color: '#f59e0b',
    order: 2,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 48,
    actionLabel: 'Gửi lộ trình & Báo giá',
    description: 'Đã kết nối thành công, phụ huynh quan tâm chương trình học và đang tìm hiểu',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-qt-1',
        code: 'GOI_LAN_1',
        name: 'Đã gọi lần 1 (Chưa chốt)',
        color: '#fbbf24',
        origin: 'custom',
        leadCount: 112,
        isActive: true,
      },
      {
        id: 'sub-qt-2',
        code: 'GOI_LAN_2',
        name: 'Đã gọi lần 2 (Đang chăm)',
        color: '#f59e0b',
        origin: 'custom',
        leadCount: 76,
        isActive: true,
      },
      {
        id: 'sub-qt-3',
        code: 'HEN_GOI_LAI',
        name: 'Hẹn gọi lại sau',
        color: '#d97706',
        origin: 'custom',
        suggestsCallback: true,
        leadCount: 65,
        description: 'Phụ huynh bận, hẹn gọi lại theo giờ',
        isActive: true,
      },
      {
        id: 'sub-qt-4',
        code: 'GUI_BAO_GIA',
        name: 'Đã gửi lộ trình & Báo giá',
        color: '#ea580c',
        origin: 'custom',
        leadCount: 42,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-tad',
    code: 'TAD',
    name: '[T2] Đánh giá & Học thử',
    phaseGroup: 'T2',
    phaseGroupLabel: 'Đánh giá & Học thử',
    color: '#ec4899',
    order: 3,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 72,
    actionLabel: 'Đặt lịch test / Học thử',
    description: 'Học viên đặt lịch test đầu vào, tham gia học thử và nhận kết quả xếp lớp học thuật',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-tad-1',
        code: 'DA_DAT_TEST',
        name: 'Đã đặt lịch kiểm tra năng lực',
        color: '#f87171',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Tạo phiếu Booking Test',
        leadCount: 68,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-2',
        code: 'VANG_TEST',
        name: 'Vắng test (No-show)',
        color: '#dc2626',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Học viên vắng mặt giờ test',
        requiresNote: true,
        leadCount: 16,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-3',
        code: 'DA_DANG_KY_THU',
        name: 'Đã đăng ký học thử',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lớp học thử (Trial Class)',
        systemEventTrigger: 'Tạo lịch học thử',
        leadCount: 38,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tad-4',
        code: 'CHUA_GIAO_GV',
        name: 'Chưa phân công giáo viên test',
        color: '#a855f7',
        origin: 'custom',
        leadCount: 12,
        isActive: true,
      },
      {
        id: 'sub-dtt-1',
        code: 'CHO_GV_CHAM',
        name: 'Chờ giáo viên nhập kết quả',
        color: '#880e4f',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Học viên hoàn thành bài test',
        leadCount: 22,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dtt-2',
        code: 'HOAN_TAT_THU',
        name: 'Hoàn tất buổi học thử',
        color: '#9333ea',
        origin: 'system',
        systemModule: 'trial_class',
        systemModuleLabel: 'Lớp học thử (Trial Class)',
        systemEventTrigger: 'Điểm danh có mặt lớp học thử',
        leadCount: 29,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-1',
        code: 'DAT_SUPERKIDS',
        name: 'Đạt trình độ SuperKids',
        color: '#ec4899',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level SuperKids',
        leadCount: 45,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-2',
        code: 'DAT_FLYERS',
        name: 'Đạt trình độ Flyers',
        color: '#d946ef',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level Flyers',
        leadCount: 32,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-3',
        code: 'DAT_KINDY',
        name: 'Đạt trình độ Kindy Mầm non',
        color: '#a855f7',
        origin: 'system',
        systemModule: 'booking_test',
        systemModuleLabel: 'Lịch kiểm tra (Booking Test)',
        systemEventTrigger: 'Giáo viên xác nhận level Kindy',
        leadCount: 18,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-tl-4',
        code: 'CHO_PH_XAC_NHAN',
        name: 'Chờ phụ huynh duyệt lộ trình',
        color: '#6366f1',
        origin: 'custom',
        leadCount: 28,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-dentt',
    code: 'DENTT',
    name: '[T3] Xác nhận nhập học (Chờ chốt deal)',
    phaseGroup: 'T3',
    phaseGroupLabel: 'Chốt Deal & Nhập học',
    color: '#0d9488',
    order: 4,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 48,
    actionLabel: 'Xác nhận nộp phí / Đặt cọc',
    description: 'Phụ huynh đồng ý ghi danh, hẹn nộp tiền mặt, chờ chuyển khoản hoặc cọc giữ chỗ',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-dentt-1',
        code: 'HEN_NOP_TIEN_MAT',
        name: 'Hẹn nộp tiền mặt tại cơ sở',
        color: '#059669',
        origin: 'custom',
        leadCount: 34,
        suggestsCallback: true,
        description: 'Phụ huynh hẹn ngày giờ đến trung tâm/cơ sở để nộp tiền mặt hoặc quẹt thẻ POS',
        isActive: true,
      },
      {
        id: 'sub-dentt-2',
        code: 'CHO_CHUYEN_KHOAN',
        name: 'Chờ chuyển khoản học phí',
        color: '#0284c7',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Chọn phương thức chuyển khoản',
        leadCount: 26,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dentt-3',
        code: 'DA_THU_COC',
        name: 'Đã cọc học phí (50%)',
        color: '#0d9488',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Xác nhận phiếu thu cọc',
        leadCount: 21,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-dentt-4',
        code: 'GIU_CHO_24H',
        name: 'Giữ chỗ ưu đãi trong 24h',
        color: '#eab308',
        origin: 'custom',
        leadCount: 15,
        suggestsCallback: true,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-order',
    code: 'T4',
    name: '[T4] Xử lý Đơn hàng & Vận đơn',
    phaseGroup: 'T4',
    phaseGroupLabel: 'Vận đơn & Thu phí',
    color: '#f97316',
    order: 5,
    stageType: 'in_progress',
    isSystemCore: false,
    slaHours: 48,
    actionLabel: 'Xử lý đơn & Giao vận',
    description: 'Đóng gói giáo trình/học liệu, bàn giao đơn vị vận chuyển (NVC) hoặc đối soát thanh toán chuyển khoản',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-t4-cgh',
        code: 'CGH',
        name: 'Chờ giao hàng',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Tạo phiếu xuất kho giáo trình',
        leadCount: 18,
        isActive: true,
      },
      {
        id: 'sub-t4-dgnvc',
        code: 'DGNVC',
        name: 'Đã gửi NVC',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Bàn giao bưu tá lấy hàng',
        leadCount: 32,
        isActive: true,
      },
      {
        id: 'sub-t4-dgh',
        code: 'DGH',
        name: 'Đang giao hàng',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Bưu cục phát hàng',
        leadCount: 24,
        isActive: true,
      },
      {
        id: 'sub-t4-gtc',
        code: 'GTC',
        name: 'Giao thành công',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'orders',
        systemModuleLabel: 'Đơn hàng (Orders)',
        systemEventTrigger: 'Khách ký nhận bưu phẩm',
        leadCount: 45,
        isActive: true,
      },
      {
        id: 'sub-t4-cdh',
        code: 'CDH',
        name: 'Chờ duyệt hoàn',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 7,
        description: 'Khách từ chối nhận hoặc shipper báo không phát được',
        isActive: true,
      },
      {
        id: 'sub-t4-danghh',
        code: 'DANGHH',
        name: 'Đang hoàn hàng',
        color: '#ef4444',
        origin: 'custom',
        leadCount: 5,
        isActive: true,
      },
      {
        id: 'sub-t4-dahh',
        code: 'DAHH',
        name: 'Đã hoàn hàng',
        color: '#ef4444',
        origin: 'custom',
        leadCount: 6,
        isActive: true,
      },
      {
        id: 'sub-t4-tl',
        code: 'TL',
        name: 'Thất lạc',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 2,
        isActive: true,
      },
      {
        id: 'sub-t4-t-datt1p',
        code: 'T_DATT1P',
        name: 'Thanh toán 1 phần',
        color: '#ef4444',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Xác nhận thu 1 phần tiền',
        leadCount: 14,
        isActive: true,
      },
      {
        id: 'sub-t4-bank',
        code: 'BANK',
        name: 'Chờ đối soát Bank',
        color: '#84cc16',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Chờ giao dịch ngân hàng khớp',
        leadCount: 20,
        isActive: true,
      },
    ],
  },
  {
    id: 'stage-won',
    code: 'T5',
    name: '[T5] Hoàn tất & Thành công (Won)',
    phaseGroup: 'T5',
    phaseGroupLabel: 'Thành công',
    color: '#10b981',
    order: 6,
    stageType: 'won',
    isSystemCore: true,
    actionLabel: 'Xếp lớp học viên',
    description: 'Đã nhận đủ tiền (COD/Bank), kế toán đối soát hoàn tất và đưa học viên vào lớp học chính thức',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-t5-dncod',
        code: 'DNCOD',
        name: 'Đã nhận COD',
        color: '#84cc16',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Đơn vị vận chuyển đối soát trả tiền COD',
        leadCount: 64,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t5-dnbank',
        code: 'DNBANK',
        name: 'Đã nhận bank',
        color: '#84cc16',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Kế toán xác nhận nhận tiền tài khoản',
        leadCount: 88,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t5-t-tc1p',
        code: 'T_TC1P',
        name: 'Thành công 1 phần',
        color: '#0d9488',
        origin: 'system',
        systemModule: 'payment_receipts',
        systemModuleLabel: 'Thu ngân (Payment Receipts)',
        systemEventTrigger: 'Chốt hoàn tất module đầu',
        leadCount: 19,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-t5-t-tc',
        code: 'T_TC',
        name: 'Thành công',
        color: '#10b981',
        origin: 'system',
        systemModule: 'class_placement',
        systemModuleLabel: 'Xếp lớp (Class Placement)',
        systemEventTrigger: 'Đã đóng đủ học phí và xếp vào lớp chính thức',
        leadCount: 110,
        isActive: true,
        isSystemCore: true,
      },
    ],
  },
  {
    id: 'stage-lost',
    code: 'LOST',
    name: 'Thất bại & Dừng chăm sóc (Lost)',
    phaseGroup: 'terminal',
    phaseGroupLabel: 'Dừng chăm sóc',
    color: '#64748b',
    order: 7,
    stageType: 'global_lost',
    isSystemCore: true,
    actionLabel: 'Chuyển Kho Ủ ấm / DNC',
    description: 'Phụ huynh từ chối đăng ký, chuyển vào kho ủ ấm lưu trữ kèm lý do chi tiết',
    isActive: true,
    subStatuses: [
      {
        id: 'sub-fail-1',
        code: 'CHE_PHI_CAO',
        name: 'Chê học phí cao',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 84,
        description: 'Không đủ ngân sách hoặc so sánh giá',
        isActive: true,
      },
      {
        id: 'sub-fail-2',
        code: 'NHA_XA',
        name: 'Nhà xa cơ sở / Không tiện đưa đón',
        color: '#f97316',
        origin: 'custom',
        leadCount: 62,
        isActive: true,
      },
      {
        id: 'sub-fail-3',
        code: 'HOC_CHO_KHAC',
        name: 'Đã chọn trung tâm khác',
        color: '#e11d48',
        origin: 'custom',
        requiresNote: true,
        leadCount: 48,
        isActive: true,
      },
      {
        id: 'sub-fail-4',
        code: 'KHONG_LIEN_LAC_DUOC',
        name: 'Không liên lạc được (>5 lần gọi)',
        color: '#64748b',
        origin: 'system',
        systemModule: 'call_log',
        systemModuleLabel: 'Tổng đài & Cuộc gọi',
        systemEventTrigger: 'Vượt ngưỡng tối đa số lần gọi không nghe',
        leadCount: 39,
        isActive: true,
        isSystemCore: true,
      },
      {
        id: 'sub-thua-1',
        code: 'DTT_GIA_RE',
        name: 'Đối thủ học phí rẻ hơn',
        color: '#475569',
        origin: 'custom',
        requiresNote: true,
        leadCount: 28,
        isActive: true,
      },
      {
        id: 'sub-thua-2',
        code: 'DTT_GAN_NHA',
        name: 'Đối thủ gần nhà hơn',
        color: '#334155',
        origin: 'custom',
        leadCount: 19,
        isActive: true,
      },
      {
        id: 'sub-klp-1',
        code: 'CHAN_CUOC_GOI',
        name: 'Yêu cầu không làm phiền / Chặn gọi',
        color: '#ef4444',
        origin: 'custom',
        requiresNote: true,
        leadCount: 14,
        isActive: true,
      },
      {
        id: 'sub-huy-1',
        code: 'HUY_KE_HOACH',
        name: 'Thay đổi kế hoạch gia đình',
        color: '#94a3b8',
        origin: 'custom',
        leadCount: 22,
        isActive: true,
      },
      {
        id: 'sub-huy-2',
        code: 'CHUYEN_NHA',
        name: 'Chuyển chỗ ở / Đi tỉnh',
        color: '#64748b',
        origin: 'custom',
        leadCount: 15,
        isActive: true,
      },
    ],
  },
]

export const MOCK_CALL_DISPOSITIONS: CallDispositionConfig[] = [
  {
    id: 'cd-1',
    code: 'SS',
    name: 'Số sai / Nhầm số',
    category: 'invalid_number',
    categoryLabel: 'Số không hợp lệ',
    color: '#333333',
    triggersCallback: false,
    description: 'Số điện thoại không có thực, thiếu số, hoặc người nghe báo nhầm người',
    isActive: true,
  },
  {
    id: 'cd-2',
    code: 'KNM',
    name: 'Không nghe máy',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#0d47a1',
    triggersCallback: true,
    defaultCallbackMinutes: 180,
    description: 'Đổ chuông nhưng không bắt máy. Hệ thống tự động xếp lịch gọi lại sau 3 tiếng',
    isActive: true,
  },
  {
    id: 'cd-3',
    code: 'GL',
    name: 'Hẹn gọi lại',
    category: 'retry_scheduled',
    categoryLabel: 'Hẹn tương tác lại',
    color: '#ab47bc',
    triggersCallback: true,
    defaultCallbackMinutes: 1440,
    description: 'Phụ huynh đang bận họp/lái xe, yêu cầu gọi lại vào khung giờ hẹn cụ thể',
    isActive: true,
  },
  {
    id: 'cd-4',
    code: 'BUSY',
    name: 'Máy bận / Từ chối cuộc gọi',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#e65100',
    triggersCallback: true,
    defaultCallbackMinutes: 60,
    description: 'Máy bận hoặc phụ huynh chủ động gạt máy. Xếp lịch gọi lại sau 1 tiếng',
    isActive: true,
  },
  {
    id: 'cd-5',
    code: 'UNREACHABLE',
    name: 'Thuê bao / Tắt máy',
    category: 'unreachable',
    categoryLabel: 'Không liên lạc được',
    color: '#5c6bc0',
    triggersCallback: true,
    defaultCallbackMinutes: 360,
    description: 'Tổng đài báo thuê bao không liên lạc được, ngoài vùng phủ sóng',
    isActive: true,
  },
  {
    id: 'cd-6',
    code: 'CONNECTED',
    name: 'Đã kết nối thành công & Trao đổi',
    category: 'connected',
    categoryLabel: 'Kết nối thành công',
    color: '#2e7d32',
    triggersCallback: false,
    description: 'Tư vấn viên đã trao đổi trực tiếp với phụ huynh về nhu cầu khóa học',
    isActive: true,
  },
]

export const MOCK_LEGACY_MAPPINGS: LegacyMappingItem[] = [
  // Giai đoạn T0
  {
    id: 'map-1',
    legacyPhase: 'T0',
    legacyCode: 'SS',
    legacyName: 'Số sai',
    legacyColor: '#333333',
    canDelete: false,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Số không hợp lệ (SS)',
    modernRationale: 'Tách thành kết quả cuộc gọi; số điện thoại được đưa vào danh sách đen sàng lọc, không tạo Lead rác.',
  },
  {
    id: 'map-2',
    legacyPhase: 'T0',
    legacyCode: 'DL',
    legacyName: 'Kho chung',
    legacyColor: '#5b32a8',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Chung Phân Bổ (KHO_DL)',
    modernRationale: 'Được nâng cấp thành Data Pool trung tâm, phân phối dữ liệu cho đội ngũ qua thuật toán Round-Robin.',
  },
  {
    id: 'map-3',
    legacyPhase: 'T0',
    legacyCode: 'KNEW',
    legacyName: 'Kho NEW',
    legacyColor: '#5b32a8',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Tiếp Nhận Mới (KHO_NEW)',
    modernRationale: 'Nơi gom data thô từ các chiến dịch trực tuyến (Landing Page, Mạng xã hội) trước khi tự động kiểm tra trùng.',
  },
  {
    id: 'map-4',
    legacyPhase: 'T0',
    legacyCode: 'CL',
    legacyName: 'Kho lọc',
    legacyColor: '#795548',
    canDelete: false,
    modernDomain: 'Data Pool',
    modernTarget: 'Kho Dữ liệu: Kho Sàng Lọc & Tái Khai Thác (KHO_R)',
    modernRationale: 'Kho chứa các liên hệ bị thu hồi do quá hạn xử lý (SLA) hoặc các cơ hội cũ cần ủ ấm 60-90 ngày.',
  },

  // Giai đoạn T1
  {
    id: 'map-5',
    legacyPhase: 'T1',
    legacyCode: 'NEW',
    legacyName: 'New',
    legacyColor: '#64c8f5',
    canDelete: false,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Mới tiếp nhận (NEW)',
    modernRationale: 'Bước mở đầu của hành trình tuyển sinh sau khi Lead được gán cho tư vấn viên phụ trách.',
  },
  {
    id: 'map-6',
    legacyPhase: 'T1',
    legacyCode: 'KNM',
    legacyName: 'KNM',
    legacyColor: '#0d47a1',
    canDelete: false,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Không nghe máy (KNM)',
    modernRationale: 'Lưu vào lịch sử cuộc gọi với bộ đếm số lần gọi; Lead vẫn giữ nguyên trạng thái tư vấn.',
  },
  {
    id: 'map-7',
    legacyPhase: 'T1',
    legacyCode: 'GL',
    legacyName: 'GL',
    legacyColor: '#ab47bc',
    canDelete: true,
    modernDomain: 'Call Disposition',
    modernTarget: 'Mã Cuộc gọi: Hẹn gọi lại (GL)',
    modernRationale: 'Lưu thành lịch hẹn tương tác kèm thời gian nhắc nhở tự động trên bảng điều khiển của nhân sự.',
  },
  {
    id: 'map-8',
    legacyPhase: 'T1',
    legacyCode: 'QT',
    legacyName: 'Quan tâm',
    legacyColor: '#ff9800',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đang tư vấn (QT)',
    modernRationale: 'Khách hàng có nhu cầu học tập rõ ràng, đang thảo luận chương trình học và thời gian học.',
  },
  {
    id: 'map-9',
    legacyPhase: 'T1',
    legacyCode: 'TAD',
    legacyName: 'Test/Demo',
    legacyColor: '#e57373',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Hẹn Kiểm tra / Trải nghiệm (TAD)',
    modernRationale: 'Tự động liên kết và mở phiếu đặt lịch tại phân hệ Kiểm tra năng lực (/app/booking_test).',
  },
  {
    id: 'map-10',
    legacyPhase: 'T1',
    legacyCode: 'DTT',
    legacyName: 'Đã Test /Demo',
    legacyColor: '#880e4f',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đã tham gia Test / Demo (DTT)',
    modernRationale: 'Ghi nhận sự có mặt của học viên tại buổi đánh giá hoặc lớp học thử (/app/trial_class).',
  },
  {
    id: 'map-11',
    legacyPhase: 'T1',
    legacyCode: 'TLTTT',
    legacyName: 'Ra level',
    legacyColor: '#f48fb1',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Đã có kết quả xếp lớp (TLTTT)',
    modernRationale: 'Giáo viên/Chuyên môn hoàn tất phiếu chấm điểm năng lực và đề xuất trình độ khóa học tương ứng.',
  },
  {
    id: 'map-12',
    legacyPhase: 'T1',
    legacyCode: 'DENTT',
    legacyName: 'Confirm',
    legacyColor: '#00897b',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Phễu: Chờ chốt deal (DENTT)',
    modernRationale: 'Phụ huynh đồng ý phương án đào tạo, chuyển sang giai đoạn tạo đơn hàng và chọn hình thức thu phí.',
  },
  {
    id: 'map-13',
    legacyPhase: 'T1',
    legacyCode: 'DADENTT',
    legacyName: 'Đã đến TT',
    legacyColor: '#00bcd4',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Lịch sử Sự kiện: Check-in tại Cơ sở',
    modernRationale: 'Là một mốc sự kiện điểm danh tại quầy tiếp đón/lễ tân, không đóng vai trò làm trạng thái phễu.',
  },
  {
    id: 'map-14',
    legacyPhase: 'T1',
    legacyCode: 'SDT',
    legacyName: 'Tiềm năng',
    legacyColor: '#f44336',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Thuộc tính Lead: Độ ưu tiên cao (Hot Lead)',
    modernRationale: 'Chuyển thành huy hiệu cờ đánh giá tiềm năng cao trên dòng thông tin của Lead.',
  },

  // Giai đoạn T2
  {
    id: 'map-15',
    legacyPhase: 'T2',
    legacyCode: 'FAIL',
    legacyName: 'Fail',
    legacyColor: '#9e9e9e',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Thất bại - Không chuyển đổi',
    modernRationale: 'Trạng thái kết thúc thất bại toàn cục (Global Lost), bắt buộc chọn lý do: Giá cao, Chưa phù hợp thời gian...',
  },
  {
    id: 'map-16',
    legacyPhase: 'T2',
    legacyCode: 'THUA',
    legacyName: 'Thua',
    legacyColor: '#37474f',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Thua đối thủ cạnh tranh',
    modernRationale: 'Trạng thái kết thúc thất bại để phục vụ báo cáo phân tích đối thủ cạnh tranh trên địa bàn.',
  },
  {
    id: 'map-17',
    legacyPhase: 'T2',
    legacyCode: 'KLP',
    legacyName: 'Ko Lphiền',
    legacyColor: '#546e7a',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Cờ Hồ sơ: Danh sách Không làm phiền (DNC)',
    modernRationale: 'Đánh dấu hồ sơ vào danh sách đen không gọi, tự động chặn mọi chiến dịch liên hệ tiếp theo.',
  },
  {
    id: 'map-18',
    legacyPhase: 'T2',
    legacyCode: 'HUY',
    legacyName: 'Hủy',
    legacyColor: '#9e9e9e',
    canDelete: true,
    modernDomain: 'Sales Pipeline',
    modernTarget: 'Trạng thái Kết thúc: Khách hủy đăng ký',
    modernRationale: 'Dừng quy trình tuyển sinh khi khách hàng chủ động hủy lịch test hoặc tạm dừng kế hoạch học.',
  },
  {
    id: 'map-19',
    legacyPhase: 'T2',
    legacyCode: 'DG',
    legacyName: 'Đã gộp',
    legacyColor: '#a1887f',
    canDelete: true,
    modernDomain: 'Master Profile',
    modernTarget: 'Cơ chế Hồ sơ: Bản ghi đã được Gộp (Merged)',
    modernRationale: 'Dữ liệu được hợp nhất vào hồ sơ chính thông qua công cụ giải quyết trùng lặp (Deduplication).',
  },

  // Giai đoạn T3
  {
    id: 'map-20',
    legacyPhase: 'T3',
    legacyCode: 'BANK',
    legacyName: 'Bank',
    legacyColor: '#afb42b',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Phương thức Thanh toán: Chuyển khoản (Bank Transfer)',
    modernRationale: 'Thuộc tính hình thức thanh toán của đơn hàng tại phân hệ Đơn hàng & Phiếu thu (/app/orders).',
  },
  {
    id: 'map-21',
    legacyPhase: 'T3',
    legacyCode: 'COD',
    legacyName: 'COD',
    legacyColor: '#2e7d32',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Phương thức Thanh toán: Thu tiền khi nhận (COD)',
    modernRationale: 'Áp dụng cho đơn hàng có kèm bộ học liệu/giáo trình vật lý giao đến tận nhà.',
  },
  {
    id: 'map-22',
    legacyPhase: 'T3',
    legacyCode: 'CGH',
    legacyName: 'Chờ giao hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Chờ đóng gói & Bàn giao',
    modernRationale: 'Chuyển vào phân hệ Bàn giao & Giao hàng (/app/order_fulfillment), thủ kho xử lý đóng gói.',
  },
  {
    id: 'map-23',
    legacyPhase: 'T3',
    legacyCode: 'DGNVC',
    legacyName: 'Đã gửi NVC',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã bàn giao Đơn vị Vận chuyển',
    modernRationale: 'Đã có mã vận đơn từ bưu điện (ViettelPost, GHTK, GHN), đang chờ hãng vận chuyển tiếp nhận.',
  },
  {
    id: 'map-24',
    legacyPhase: 'T3',
    legacyCode: 'DGH',
    legacyName: 'Đang giao hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đang phát hàng (In Transit)',
    modernRationale: 'Shipper đang trên đường giao bưu phẩm sách/học liệu đến địa chỉ của học viên.',
  },
  {
    id: 'map-25',
    legacyPhase: 'T3',
    legacyCode: 'GTC',
    legacyName: 'Giao thành công',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Giao hàng thành công',
    modernRationale: 'Bưu phẩm đã đến tay phụ huynh, xác nhận hoàn tất khâu giao tài liệu đào tạo.',
  },
  {
    id: 'map-26',
    legacyPhase: 'T3',
    legacyCode: 'CDH',
    legacyName: 'Chờ duyệt hoàn',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Chờ duyệt hoàn hàng',
    modernRationale: 'Giao không thành công sau 3 lần gọi, bưu điện gửi yêu cầu phê duyệt chuyển hoàn.',
  },

  // Giai đoạn T4
  {
    id: 'map-27',
    legacyPhase: 'T4',
    legacyCode: 'DDH',
    legacyName: 'Đã duyệt hoàn',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã duyệt hoàn',
    modernRationale: 'Quản lý vận hành xác nhận đồng ý cho bưu kiện quay đầu về kho sách trung tâm.',
  },
  {
    id: 'map-28',
    legacyPhase: 'T4',
    legacyCode: 'DANGHH',
    legacyName: 'Đang hoàn hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đang quay đầu hoàn kho',
    modernRationale: 'Bưu điện đang luân chuyển gói học liệu về lại cơ sở lưu kho ban đầu.',
  },
  {
    id: 'map-29',
    legacyPhase: 'T4',
    legacyCode: 'DAHH',
    legacyName: 'Đã hoàn hàng',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Đã nhập kho hoàn',
    modernRationale: 'Thủ kho nhận lại sách và hoàn trả số lượng vào tồn kho giáo trình.',
  },
  {
    id: 'map-30',
    legacyPhase: 'T4',
    legacyCode: 'TL',
    legacyName: 'Thất lạc',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Fulfillment',
    modernTarget: 'Vận chuyển Bưu phẩm: Bưu kiện thất lạc',
    modernRationale: 'Ghi nhận sự cố vận chuyển để lập hồ sơ bồi thường với bên đơn vị chuyển phát.',
  },
  {
    id: 'map-31',
    legacyPhase: 'T4',
    legacyCode: 'DH',
    legacyName: 'Đã hủy',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Đơn hàng: Đã hủy đơn hàng (Order Canceled)',
    modernRationale: 'Đơn hàng mua khóa học bị hủy bỏ, hóa đơn tài chính bị thu hồi.',
  },
  {
    id: 'map-32',
    legacyPhase: 'T4',
    legacyCode: 'T_DATT1',
    legacyName: 'Thanh toán 1 phần',
    legacyColor: '#ef5350',
    canDelete: true,
    modernDomain: 'Order & Payment',
    modernTarget: 'Trạng thái Thanh toán: Đã cọc / Trả góp đợt 1',
    modernRationale: 'Quản lý công nợ trên đơn hàng, hỗ trợ phụ huynh đóng học phí làm nhiều đợt.',
  },
]
